centrifuge/centrifuge-chain

runtime/src/anchor/mod.rs, runtime/src/anchor/tests.rs, runtime/src/fees.rs, runtime/src/nfts.rs
closes centrifuge/roadmap#130
This PR ensures the state rent is paid to block author.
`pallet_authorship::author()` returns either the primary or secondary author of the current block this is being included in. 
More on this is found here - https://github.com/paritytech/substrate/blob/master/frame/babe/src/lib.rs#L207
I have updated the `fees` module to take the `to` account to which the fees will be transferred to. Even though we use this for anchor state rent, it would be more reusable to take `from` and `to` rather than `fees` module implementing `pallet_authorship`
=> transfer anchor state rent to block author

src/chain_spec.rs
The order of the accounts need to be lexicographical for Fulvous hardcoded multi-account setup.
=> Fix MultiAcc order for fulvous

.travis.yml, ci/check_pr.sh, ci/check_runtime_changes.sh
Closes issue #200 
The ci-script behavior:
Any pull request to the `centrifuge-chain` will **auto-fail** if
- there are changes in the `runtime/` and PR is labeled as `breakapi` and `spec_version` is not changed in `runtime/src/lib.rs`.
- there are changes in the `runtime/` and PR is NOT labeled as `breakapi` and `impl_version` is not changed in `runtime/src/lib.rs`.
The script should ensure that changes in `runtime/` will have a appropriate change in the `version`
=> Add ci script to auto-fail PR if changes in runtime version is not met with the defined conditions

Cargo.lock, runtime/Cargo.lock, runtime/Cargo.toml, runtime/src/bridge.rs, runtime/src/lib.rs, runtime/src/nfts.rs
This is based on [ChainSafe/chainbridge](https://github.com/ChainSafe/chainbridge-substrate) example pallet.
- rename `bridge` module as `pallet_bridge` to have a clear distinction from `chainbridge`
- needs enhancements on the doc comment on the module functions
- `transfer_hash`
- `transfer_native`
- `transfer` 
- `remark`
- Erc721 `parameter_types` is not included.
```rust
parameter_types!{
pub const Erc721Id: bridge::ResourceId = bridge::derive_resource_id(1, &blake2_128(b"NFT"));
}
```
- No `GenesisConfig` defined in `chain_spec`.
- in the chainsafe example `bridge_pallet` has no defined `decl_storage!`
- `bridge_pallet` inherits on `chainbridge::Trait` where a `decl_storage` is defined.
- will this have an entry into the `GenesisConfig` in `chain_spec`?
```rust
pub trait Trait: …
```
=> Initial code for pallet_bridge based on chainsafe/chainbridge example

runtime/src/bridge.rs, runtime/src/lib.rs
Fixes conflicting storage names with ChainSafe Bridge storage pallet.
=> Rename PalletBridge storage

runtime/Cargo.toml, runtime/src/lib.rs
The `wasm-builder-package` at the specified commit has version 1.0.6:
https://github.com/centrifuge/substrate/blob/e271ae7fda72a7ad55ff3c216b8b2abae0ae31fd/utils/wasm-builder-runner/Cargo.toml#L3
=> runtime/Cargo.toml: fix wasm-builder-runner version

.github/workflows/build.yml, .gitignore, flake.lock, flake.nix
This uses `ENTRYPOINT` instead of `CMD`, which is the correct way to set the
image's "base" command, since it doesn't get overwritten by arguments passed to
`docker run`. 
See [here](https://aws.amazon.com/blogs/opensource/demystifying-entrypoint-cmd-docker/) for an explanation.
Additionally, this PR:
- moves the Docker-related parts of the workflow file behind a check, ensuring they only run on the upstream repo and not on forks
- fixes the Docker tag, adding hours, minutes and seconds to the timestamp
- prepends `/bin` to the `PATH`, so that Kubernetes `Deployement`s don't have to be updated.
=> Allow arguments to be passed to Docker image

.github/dependabot.yml
This will create automatic PRs to keep our actions up to date.
It will only trigger once the PR is merged though, as the file needs to be on the default branch - so we can't really test it.
=> ci: config dependabot to update GitHub Actions

Cargo.lock, runtime/Cargo.toml, runtime/src/lib.rs, runtime/src/rad_claims.rs, src/command.rs, src/service.rs
This performs a full "cargo update", since most of our dependencies are pallets. Code-wise, the changes were largely due to the XCM refactor that removed XcmHandler.
At this point, it should at least be representative of the shape that the new XCM handling code will take, based on what's in cumulus#rococo-v1. Besides actually formatting my changes, I don't expect landing any major adjustments that would cause conflicts, so this is nearly usable as a base for other work.
Still To-do before this is production ready:
=> Update to latest rococo-v1

flake.lock, flake.nix
This should ensure we don't trigger nix builds when not necessary, giving us much faster CI feedback.
We achieve this by ignoring the files listed in the `srcFilter` function, meaning that:
- they won't end up in the nix package
- a change to one of these files won't trigger a new nix build
- the respective docker image generation will be much faster
/cc @lucasvo
=> CI: skip building when source hasn't changed

src/chain_spec.rs, src/cli.rs, src/command.rs
This is necesary for compatibility with `polkadot-launch`
=> Allow specifying parachain ID for genesis from the CLI

Cargo.lock, pallets/crowdloan-claim/crowdloan-claim-reward/src/lib.rs, pallets/crowdloan-claim/src/lib.rs, pallets/crowdloan-claim/src/mock.rs, pallets/crowdloan-claim/src/tests.rs, pallets/crowdloan-claim/src/weights.rs, pallets/crowdloan-reward/src/lib.rs, pallets/crowdloan-reward/src/tests.rs
This PR is an alternative to #385. 
The difference here are that the pallets need to be initialized separately. Hence, the `Reward` trait has a smaller interface and only provides a rewarding functionality. 
Furthermore, the claim pallet is changed, in order to provide the possibility to initialize it multiple times.
=> Crowdloan Claim Pallet V2 -Alternative to  #385

runtime/src/lib.rs
This removes the `Vesting` proxy type, and replaces it with a `NonProxy` proxy type. This new proxy type forbids all proxy operations on the proxied account **except** for calling `proxy::proxy(..)` to invoke an account which is proxied by the proxied account.
=> Replace Vesting proxy with NonProxy proxy

runtime/src/bridge.rs, runtime/src/lib.rs
Previously, the chain bridge transfer checked that the total transfer
amount + fee was greater than the "free" balance in the account. This
does not take into account various types of locks that can be on an
account.
This PR changes to use the `ensure_can_withdraw` function from the
Currency trait. This function checks all locks and fails the
transaction if there is not enough available balance in the account.
=> Use `ensure_can_withdraw` in chain bridge transfers

tools/testbed/Makefile, tools/testbed/README.md, tools/testbed/automake/settings.mk, tools/testbed/docker/Dockerfile, tools/testbed/docker/docker-compose-networks.yml, tools/testbed/docker/docker-compose-services.yml
This PR implements the following features:
- A Docker-based testbed infrastructure for the Centrifuge Chain (built from source).
- Expose the Centrifuge Chain features behind the Parity Substrate API Sidecar.
- Provide Docker Compose file and Makefile to ease the bootstrap of the testbed infrastructure.
=> Testbed used to execute Centrifuge Chain behind Parity `substrate-api-sidecar`

runtime/altair/src/lib.rs, runtime/centrifuge/src/lib.rs, runtime/common/src/lib.rs, runtime/development/src/lib.rs
The previous lower bound of 1000 tokens has caused issues with
crowdloan rewards and other small vesting quantities.
=> Lower minimum vesting amount to 10 CFG/AIR

Cargo.lock, runtime/altair/Cargo.toml, runtime/altair/src/lib.rs
=> Integrates Crowdloan Pallets into Altair

README.md, scripts/init.sh
We seem to have forgotten to update some references
=> fix: Rename centrifuge-chain-runtime to centrifuge-runtime

src/chain_spec.rs, src/cli.rs, src/command.rs, src/service.rs
Just run `cargo clippy` and applied most of the suggested fixes, mostly unnecessary `clones()`, references, and conversions.
=> Apply cargo clippy fixes

Dockerfile
As we currently do not have the need to overwrite the default command and this will make our docker images more compatible with the parachain-launch script from web3-foundation, this changes the  `CMD` to `ENTRYPOINT` in the dockerfile.
=> Use ENTRYPOINT in Dockerfile

pallets/migration/src/benchmarking.rs
Currently, building the benchmarks fails to compile with the following error:
``` rust
error[E0308]: mismatched types
--> pallets/migration/src/benchmarking.rs:95:5
|
93 |   ...   let storage_vesting_info: VestingInfo<<<T as pallet_vesting::Config>::Currency as Currency<<T as frame_system::Config>::AccountId>>...
|  _________________________________-
94 | | ...   T::BlockNumber> =
| |_____________________- expected due to this
95 |   ...       pallet_vesting::Vesting::<T>::try_get(id).unwrap();
|             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ expected struct `VestingInfo`, found struct `frame_support::BoundedVec`
```
It seems that the Api has changed, which we fix in this PR. Please check carefully whether my _fix_ is fair.
=> Fix migration benchmarking

pallets/crowdloan-claim/src/benchmarking.rs, pallets/migration/src/benchmarking.rs
Back-porting the migration/benchmarking compilation error fix (https://github.com/centrifuge/centrifuge-chain/pull/540) and cleaning unused imports and unused code from `crowdloan-claim/src/benchmarking.rs`.
=> Quick broom 🧹 

pallets/claims/Cargo.toml, pallets/crowdloan-claim/Cargo.toml, pallets/fees/Cargo.toml, pallets/nft/Cargo.toml
To follow @vedhavyas's suggestion already applied to the collator-allowlist pallet.
=> chore: group optional benchmark dependencies

scripts/run_benchmark.sh
Right now, the `run_benchmark.sh` script sort of expects the `pallet` param to be formatted following the snake_case style, which does not match with the name convention for the our pallets, which causes the `output` weights file to be set to a destination that doesn't exist.
``` bash
$ ./scripts/init.sh benchmark pallet_collator_allowlist
(..)
Running `target/release/centrifuge-chain benchmark --chain=altair-dev --steps=50 --repeat=100 --pallet=pallet_collator_allowlist '--extrinsic=*' --execution=wasm --wasm-execution=compiled --heap-pages=4096 --output=./pallets/collator_allowlist/src/weights.rs --template=./scripts/frame-weight-template.hbs`
2021-12-06 14:41:45 assembling new collators for new session 0 at #0
2021-12-06 14:41:45 assembling new collators for new session 1 at #0
Error: …
```
=> benchmark: fix output dir in run_benchmark

src/main.rs, src/rpc.rs, src/service.rs
This PR extends all nodes (dev, altair, cfg) with the default rpc methods of `PaymentApi`, `SystemApi`.
=> Extend iohandler with default rpcs 

pallets/loan/src/mock.rs, pallets/tinlake-investor-pool/src/lib.rs, pallets/tinlake-investor-pool/src/mock.rs, pallets/tinlake-investor-pool/src/tests.rs, runtime/development/src/lib.rs
This also stores the interest rate in a different fixed format which
avoids some redudant conversionss for every interest calculation
Fixes #558
=> Use 27-bit fixed point for tranche interest rates

pallets/tinlake-investor-pool/src/lib.rs, pallets/tinlake-investor-pool/src/tests.rs
Min risk buffer is defined as `<subordinate tranche sum>/<total value>`.
The previous definition was `<subordinate tranche sum>/<tranche value>`.
=> Switch from sub ratio to risk buffer for tranche constraints

runtime/altair/src/lib.rs, runtime/centrifuge/src/lib.rs, runtime/common/src/lib.rs, runtime/development/src/lib.rs
This PR adds a type of `type RootOr<O>  = EnsureOneOf<EnsureRoot, O>`. When using this as the origin type for an admin Origin of `0`, this ensures, that root is always also able to call as admin.
I think as a general rule we should always use this type for any kind of admin origin. This ensures that democracy can always act as an admin.
=> Adds type to ensure root is admin

libs/common-traits/src/lib.rs, libs/common-types/src/lib.rs, libs/common-types/src/tests.rs
The tests for previously required an unstable feature which made compiling the pallets or runtimes without a nighty compiler version impossible. 
This was not needed and this PR removes the unstable feature.
=> Remove unnescesary unstable feature

pallets/loans/src/test_utils.rs, pallets/pools/src/lib.rs, pallets/pools/src/mock.rs, pallets/pools/src/tests.rs
This PR ensures that tranche order is from most junior to senior.
For easier calculations for rebalancing, price calculations etc... we reverse the order to go from most senior to junior. The reverse is applied on the results if necessary
=> reverse tranche order

libs/common-traits/src/lib.rs, pallets/loans/src/tests.rs, pallets/permissions/src/lib.rs, pallets/pools/Cargo.toml, pallets/pools/src/lib.rs, pallets/pools/src/tests.rs, pallets/pools/src/tranche.rs
I will split this refactoring into multiple smaller chunks. Although, this will duplicate a little work, I hope that the reviewing process will be better and we can follow more on the changes and discuss them. 
This part does:
* Move all tranche related structures into the tranche.rs file
* Wrap the two `Vec<Tranche>` & `Vec<EpochExecutionTranche>` structs into new types
* Implement some logic like the accumulation of supplies of all pools in methods of the new types
* Remove the role approval logic from the pool api
* Adapt tests and mocks accordingly
* Makes `Order` an `OptionQuery`
=> Pool Refactor - Part 1 - Move tranche related structures

runtime/development/src/lib.rs
I forgot to bump this value after bumping the crate version in #637 🌵
=> development: Update spec_version to 1001 (0.10.1)

pallets/loans/src/benchmarking.rs, pallets/loans/src/functions.rs, pallets/loans/src/lib.rs, pallets/loans/src/tests.rs, pallets/loans/src/types.rs
This changes the NAVUpdated event to have an `exact` parameter, and
adds inexact NAVUpdated events for loan actions which modify the NAV.
Closes #641
=> Emit NAVUpdated event on borrow, repay, writeoff

pallets/collator-allowlist/src/lib.rs, pallets/fees/src/lib.rs
Quick one, just adding `[cfg(feature = "runtime-benchmarks")]` where it's currently missing and deload the main build from including benchmarking-related stuff.
=> Add missing `[cfg(feature = "runtime-benchmarks")]`

Cargo.lock, pallets/claims/src/lib.rs, runtime/development/src/lib.rs, runtime/integration-tests/Cargo.toml, runtime/integration-tests/src/kusama_test_net.rs, runtime/integration-tests/src/xcm_transfers.rs
After the update to Polkadot v0.9.17, we broke these tests.
Here, we fix that by reverting some of the changes that appeared correct when performing  the update and [use a fork](https://github.com/shaunxw/xcm-simulator/pull/25) to fix compilation errors caused by duplicated dependencies.
=> Fix runtime-integration xcm tests

pallets/pools/src/benchmarking.rs, runtime/development/Cargo.toml
* Build `chainbridge` pallet in Development runtime with the feature
* Update pools benchmarks to pass an admin account ID
=> Fix compilation with `runtime-benchmarks`

Cargo.lock, libs/common-traits/src/lib.rs, libs/common-types/src/tokens.rs, libs/proofs/Cargo.toml, pallets/loans/src/test_utils.rs, pallets/loans/src/tests.rs, pallets/pools/Cargo.toml, pallets/pools/src/benchmarking.rs, pallets/pools/src/lib.rs, pallets/pools/src/mock.rs, pallets/pools/src/solution.rs, pallets/pools/src/tests.rs, pallets/pools/src/tranche.rs, pallets/pools/src/weights.rs, runtime/common/src/impls.rs
I will split this refactoring into multiple smaller chunks. Although this will duplicate a little work, I hope that the reviewing process will be better and we can follow more on the changes and discuss them.
This part does:
* Remove implicit behaviour for `pool::collect` calls, where `last_epoch_executed` is used as a maximum for the n_epoch that are collected over. Instead now it errors out. #618
* Enforce sane tranche structure #631
* Wrap bookkeeping into methods or trait #633
* Unifiy interface of reserve trait #642
* Adjust calculation of total reserve #599
=> Pool Refactor - Part 2

pallets/loans/src/mock.rs, pallets/permissions/src/lib.rs, pallets/permissions/src/mock.rs, pallets/permissions/src/tests.rs, pallets/pools/src/mock.rs, runtime/development/src/lib.rs
Previously this was unbounded, which is a potential DOS vector against
the chain.
Rather than taking a deposit per-assigned-role, we instead set a
"sufficiently large" limit on the roles per location and expect that
the creation of that location will handle taking a deposit for the
entire thing.
In our current usage, a "location" is a pool, so this deposit needs to
be taken by the pool pallet.
This also refactors the permissions pallet slightly to avoid using a
`map_or` with a complex default. Instead we use the built-in substrate
`try_mutate` and take a more procedural code approach to the
permissions manipulation.
=> Cap number of roles per location in permissions pallet

libs/common-traits/src/lib.rs, pallets/loans/src/lib.rs, pallets/loans/src/mock.rs, pallets/loans/src/test_utils.rs, pallets/loans/src/tests.rs, pallets/permissions/src/benchmarking.rs, pallets/permissions/src/lib.rs, pallets/permissions/src/mock.rs, pallets/permissions/src/tests.rs, pallets/permissions/src/weights.rs, pallets/pools/src/benchmarking.rs, pallets/pools/src/lib.rs, pallets/pools/src/mock.rs, pallets/pools/src/tests.rs, pallets/restricted-tokens/src/benchmarking.rs, runtime/development/src/lib.rs, runtime/development/src/weights/pallet_permissions.rs
- Closes #691
- Fixes a casing typo in the runtime
- Adds `tranche_id` to the `InvestOrderUpdated` and `RedeemOrderUpdated` events, as without this, the client does not know which tranche the order was updated for, and they need to check orders for all tranches of the pool.
=> Rename permission extrinsic names

Cargo.lock, runtime/integration-tests/Cargo.toml
My pr updating that dependency to polkadot v17 has been merged so we can
move back to use the official project.
=> Move back to `shaunxw/xcm-simulator`

scripts/init.sh
We move all the `./scripts/init.sh` by-products to `/tmp/centrifuge-chain/<sub_dir>` to have a more organised structure for the different commands.
This also fixes the latest `onboard-parachain` writting the wasm file to the project dir and thus causing an unwanted git diff.
=> scripts: improve by-product locations

pallets/loans/src/test_utils.rs, pallets/pools/src/mock.rs, pallets/pools/src/tranche.rs
Currently we are planning to use `Twox128` in order to generate `TrancheIds`.  I think this is a problem. It's seems that it is trivially to generate collisions, especially for the input data that we have, which are deterministic. 
As we only generate `TranchIds` at the setup of pools and then sparsly from time to time when a tranche is replaced or added I think it is okay to use the slower `Blake_128`
* Off-chain: generate hashes with available pool-ids and increasing tranche-counters
* Compare the generated hashes with existing tranche-ids
* If one matches: create the respective pool and replace the senior-tranche with new tranches until the `TrancheId` matches the found collision
-> We then have two pools, one normal one, one controlled by the attacker, where we have a colliding …
=> Switch TrancheId generator hash-algorithm

runtime/src/lib.rs
While testing found an error with the new code that had missing some mandatory calls:
```
2022-03-30 00:06:42.010 tokio-runtime-worker WARN slots  Encountered consensus error: ClientImport("ApplyExtrinsicFailed(Validity(TransactionValidityError::Invalid(InvalidTransaction::BadMandatory)))")
2022-03-30 00:06:45.553 tokio-runtime-worker INFO substrate  💤 Idle (0 peers), best: #123 (0xef70…4cf5), finalized #121 (0x74b9…6dba), ⬇ 0 ⬆ 0
2022-03-30 00:06:48.003 tokio-runtime-worker INFO sc_basic_authorship::basic_authorship  🙌 Starting consensus session on top of parent 0xef7097ec8015aa6bbca70791c75211ca293230ad3235c0440198711853064cf5
2022-03-30 00:06:48.022 tokio-blocking-driver ERROR sc_basic_authorship::basic_authorship  ❌️ Mandatory inherent extrinsic returned error. Block cannot be …
```
=> Add missing mandatory calls

Cargo.lock, runtime/centrifuge/Cargo.toml, runtime/centrifuge/src/lib.rs, runtime/development/src/lib.rs, src/chain_spec.rs
Along with it, we also add `pallet_nfts` and `pallet_bridge` as they are both dependencies of chainbridge.
=> centrifuge: Add chainbridge pallet

scripts/run_benchmark.sh
Removes the deprecated parameter as we now have multiple runtimes.
=> Remove -p centrifuge-runtime parameter

runtime/integration-tests/Cargo.toml
This is an alternative to proposal 1 in #774, where we keep the feature flags to allow us to keep the `chain` abstraction and thus be able to run the same tests against different runtimes while still being able to use any runtime. With this proposal, instead of following the proposal 1 by the letter, we also don't need to run the integration tests with all the different flags to make sure that all the tests are being run.
=> integration-tests: Use empty feature flags

pallets/loans/src/benchmarking.rs, pallets/loans/src/lib.rs, pallets/loans/src/tests.rs, pallets/pools/src/lib.rs, runtime/integration-tests/src/pools/pool_starts.rs
- Extend order events to include old & new order amounts
- Add event on tranche rebalancing
- Extend loan pricing event with pricing info
=> Extend pool and loan pallet events

runtime/altair/src/lib.rs
Adds a fix for the XCM integration in Altair
=> altair: Bump spec_version to 1013

Cargo.lock, Cargo.toml, runtime/altair/Cargo.toml
I forgot to also bump the Altair package version when I bumped the altair spec version so we do we it here.
=> altair: Bump package to 0.10.13

pallets/pools/src/lib.rs
Prevents panics in epoch execution due to the invest/redeem amount
changing during the submission period.
This is a temporary measure until the investments pallet can be
fully integrated.
=> Disallow updating orders during submission period

libs/common-types/src/tokens.rs, pallets/loans/src/benchmarking.rs, pallets/loans/src/mock.rs, pallets/loans/src/tests.rs, pallets/nft-sales/src/benchmarking.rs, pallets/nft-sales/src/mock.rs, pallets/nft-sales/src/tests.rs, pallets/pools/src/benchmarking.rs, pallets/pools/src/mock.rs, pallets/pools/src/tests.rs, pallets/restricted-tokens/src/mock.rs, pallets/restricted-tokens/src/tests.rs, runtime/development/src/lib.rs, runtime/integration-tests/src/lib.rs, runtime/integration-tests/src/pools/utils/genesis.rs, runtime/integration-tests/src/pools/utils/pools.rs, src/chain_spec.rs
The `CurrencyId::Usd` variant served as a placeholder for a dollar stable coin. With the introduction of the `KUSD` variant, we drop the placeholder `Usd` and use `KUSD` instead.
=> Drop CurrencyId::Usd in favour of AUSD

runtime/altair/src/xcm.rs, runtime/development/src/xcm.rs
Two things happening here:
1. Updating development > xcm.rs with latest Altair > xcm.rs, tested and running in production
2. Renaming "Air" to "Native" in development > xcm.rs
3. Swapping the Canonical trader naming for the native token - I misnamed them initially
=> xcm: Sync Altair & Dev configs & fix trader names

Cargo.lock, Cargo.toml, pallets/claims/Cargo.toml, pallets/claims/src/lib.rs, pallets/claims/src/migration.rs, pallets/claims/src/tests.rs, runtime/centrifuge/Cargo.toml, runtime/centrifuge/src/lib.rs, src/cli.rs, src/command.rs
Potential change (pending agreement) to change root hashes storage from a map to single value.
In addition adding try-runtime to verify upgrades against a live chain data. To execute:
```
cargo build --release --features=try-runtime
RUST_LOG=runtime=trace,try-runtime::cli=trace,executor=trace ./target/release/centrifuge-chain try-runtime --execution Native --chain centrifuge-local --no-spec-name-check on-runtime-upgrade live --uri wss://fullnode.parachain.centrifuge.io:443
```
=> claim root hashes value instead of map

Cargo.lock, pallets/loans/Cargo.toml, pallets/nft-sales/Cargo.toml, pallets/pools/Cargo.toml, pallets/restricted-tokens/Cargo.toml, runtime/altair/Cargo.toml, runtime/common/Cargo.toml, runtime/development/Cargo.toml, runtime/integration-tests/Cargo.toml
The fork updating to polkadot v0.9.24 [has been merged](https://github.com/open-web3-stack/open-runtime-module-library/pull/773) so we move back to using the official repo.
=> deps: Move back to official orml repo

.github/workflows/build-matrix.json
When upgrading to polkadot v0.9.24 I bumped the rust_toolchain version to 1.62.0 but that version is not published as stable yet so the CI is failing with a 404 error when trying to download that toolchain's version.
~~We fix this by moving to 1.61.0, the [latest published release](https://blog.rust-lang.org/2022/05/19/Rust-1.61.0.html).~~
-> paritytech/srtool v1.61.0 is not available yet
We fix this by moving to rust_toolchain v1.60.0.
=> ci: Fix rust_toolchain version to 1.60.0

Cargo.lock, runtime/integration-tests/Cargo.toml
My [fork's PR](https://github.com/shaunxw/xcm-simulator/pull/32#event-6824800660) has been merged to we can got back to the official repo.
=> deps: Move back to official xcm-simulator

libs/common-types/src/tests.rs
<blockquote>
🤯  **PLUS**, I jus realised this, if we choose this option I am pretty certain that we won't need to concern ourselves with the balances migration step because by dropping `CurrencyId::KUSD`, `CurrencyId::AUSD` will automatically be encoded to the value that `CurrencyId::KUSD` was, so the migration is essentially automatically done for free. I need to verify this tho!
In any case, we need to find a way of not breaking the balances when messing around with `CurrencyId` variants. Pehraps we need to implement a custom `Encode`/`Decode` impl for `CurrencyId`.
</blockquote>
_Originally posted by @NunoAlexandre in https://github.com/centrifuge/centrifuge-chain/issues/836#issuecomment-1157606927_
Whatever route we choose to we proceed with on the linked issue, it's important to have …
=> common-types: Test CurrencyId variants encoding

Cargo.lock, Cargo.toml, libs/common-traits/src/lib.rs, libs/common-types/src/lib.rs, libs/common-types/src/tokens.rs, pallets/pools/Cargo.toml, pallets/pools/src/mock.rs, pallets/restricted-tokens/Cargo.toml, pallets/restricted-tokens/src/impl_fungibles.rs, pallets/restricted-tokens/src/lib.rs, pallets/restricted-tokens/src/mock.rs, runtime/altair/Cargo.toml, runtime/altair/src/lib.rs, runtime/centrifuge/Cargo.toml, runtime/centrifuge/src/lib.rs, runtime/common/Cargo.toml, runtime/common/src/impls.rs, runtime/common/src/lib.rs, runtime/development/Cargo.toml, runtime/development/src/lib.rs, runtime/development/src/xcm.rs, runtime/integration-tests/src/xcm/setup.rs, runtime/integration-tests/src/xcm/test_net.rs, runtime/integration-tests/src/xcm/xcm_transfers.rs, src/chain_spec.rs
Part 1/2 of #825 
https://github.com/open-web3-stack/open-runtime-module-library/pull/762
https://github.com/open-web3-stack/open-runtime-module-library/pull/767
See [commit description](https://github.com/centrifuge/centrifuge-chain/pull/829/commits/0f561c11cdacb2d6e890ade1ed8681ff45420df7)
See https://github.com/centrifuge/centrifuge-chain/pull/829#discussion_r896056172
=> dev: Add `orml_asset_registry`

libs/common-types/src/tests.rs
Now that #829 has been merged, we got a new `CurrencyId` variant and should test its encoding.
=> common-types: Test CurrencyId::ForeignAsset encoding

Cargo.lock
Cumulus 0.9.24 branch has new commits that we need in, so we run `cargo
update` to update that and other dependencies that have news.
=> deps: Run `cargo update`

.github/workflows/docker.yml, Cargo.toml, Dockerfile, docker-compose-local-chain.yml, runtime/altair/Cargo.toml, runtime/altair/src/lib.rs, runtime/centrifuge/Cargo.toml, runtime/centrifuge/src/lib.rs, scripts/init.sh
**Context:**
The feedback loop of testing upgrades locally (or just some operations that require Council or Democracy) is slow. The current alternative to this is to modify the runtime code only in your dev branch to test your code but that comes with potential issues down the line, unwanted commits, extra code changes that shouldn't be required among others.
**Proposal:**
I propose to include this feature flag that we can use for certain constants that usually delay the development cycle. When this the code has been compiled with this flag, the `prod_or_fast` macro developed by parity allows to pass a test value and potentially a value read from the environment at the time of compilation (the latter is the one I used here but I do not see us using it too much)
This way when running the …
=> Include fast-runtime feature flag with some defaults

Cargo.lock, Cargo.toml, pallets/anchors/src/lib.rs, pallets/loans/src/functions.rs, pallets/loans/src/lib.rs, pallets/loans/src/types.rs, pallets/pools/src/lib.rs, pallets/pools/src/solution.rs, pallets/pools/src/tranche.rs, runtime/altair/src/lib.rs, runtime/centrifuge/src/lib.rs, runtime/common/src/apis/anchors.rs, runtime/common/src/apis/mod.rs, runtime/common/src/apis/pools.rs, runtime/common/src/lib.rs, runtime/development/src/lib.rs, src/main.rs, src/rpc/anchors.rs, src/rpc/mod.rs, src/rpc/pools.rs, src/service.rs
We resurrect [#747](https://github.com/centrifuge/centrifuge-chain/pull/796) which was git-reverted in #833 due to lots of conflicts and the need to quickly deliver on that upgrade.
- resurrect the new RPC methods that had been added, as well as follow the restructure that it had introduced.
- migrate rpc::pools to be built with `jsonrpsee`
- abstract and clean error building boiler plate code
Note: In e1282d8348b261088786909ad89bd505dffac28d I drop the params being passed to every `invalid_params_error`.  That data is just printing the params passed by the user/client, so there is really no value nor need to bloat the code with all this redundant code as far as I see. Let me know if you feel differently about it.
=> rpc: Ressurections

ci/script.sh
While this script does work on the CI, locally it will most likely fail because `RUST_TOOLCHAIN` won't hold a valid `srtool` version, leading to this error when following the Readme `Verify runtime` section:
```
λ TARGET=build-runtime RUST_TOOLCHAIN=nightly ./ci/script.sh
+ RUST_TOOLCHAIN=nightly
+ PACKAGE=altair-runtime
+ export 'RUSTFLAGS= -W unused-extern-crates'
+ RUSTFLAGS=' -W unused-extern-crates'
+ ./scripts/init.sh install-toolchain
+ RUST_TOOLCHAIN=nightly
+ echo 'Using rust toolchain: nightly'
Using rust toolchain: nightly
+ echo '*** Initializing WASM build environment'
*** Initializing WASM build environment
+ rustup update nightly
info: syncing channel updates for 'nightly-aarch64-apple-darwin'
nightly-aarch64-apple-darwin unchanged - rustc 1.64.0-nightly (27eb6d701 …
```
=> ci: Add SRTOOL_VERSION to differentiate from RUSTC

README.md
Changes:
- Added prerequisites to the Run section.
To review:
- Section "Generating a new genesis file", no longer has `id`/`protocol_id` to change in `chain_spec.rs`
=> Minor Readme updates

libs/common-traits/src/lib.rs, pallets/loans/src/lib.rs, pallets/loans/src/test_utils.rs, pallets/loans/src/types.rs, pallets/pools/src/impls.rs, pallets/pools/src/lib.rs, pallets/pools/src/tests.rs, runtime/development/src/lib.rs
Implements a generic trait that return a price for a pair of two `CurrencyId`s. For tranche tokens specifically, we almost always want to get the price denominated in the pool currency, hence to simplify the API and not require clients to know the pool currency id, we make this optional.
This is a requirement for https://github.com/centrifuge/centrifuge-chain/pull/861
In the future, the trait can also be implemented for other currencies, for example referring to an oracle pallet to get stablecoin prices.
=> Add `CurrencyPrice` trait and implement for tranche token prices

README.md
Would be nice to have this added to the Readme as the build fails unless `cmake`, `libclang-dev` are installed
=> Update build dependencies

src/rpc/anchors.rs, src/rpc/pools.rs
This PR is a minor change. It adds the option to provide an "at" parameter, at which the state the runtime-api should be called. 
I have not tested, but the API should error-out with an "UnknownState", when the block is unknown to the node. Otherwise, we can also query the status before calling the API and return early.
Closes #877
=> At at-param to rpc calls

Cargo.lock, flake.nix, runtime/altair/src/lib.rs, runtime/common/Cargo.toml, runtime/common/src/impls.rs, runtime/common/src/lib.rs, runtime/common/src/mock.rs
Proposal to increment the tx fees:
https://gov.centrifuge.io/t/rfc-increase-transaction-fees-on-centrifuge-chain-by-100x-and-use-the-fees-towards-a-token-burn/3723?u=ash
Comparison of old vs new fee (around 33 times more):
- Current balance transfer fee on a dev environment: **0.000099871597561621 CFG**
- New balance transfer fee on same dev environment **0.003287559668446737 CFG** 
Pending before merging:
Closes #809
=> [HOLD] Adapt tx fees on both altair and centrifuge by aprox. factor of 33 and transfer some % to the treasury.

.github/workflows/docs.yml, ci/create_index_for_rust_docs.sh
Closes https://github.com/centrifuge/centrifuge-chain/pull/924
It is easier to test if it's through a `branch` of the `origin` repository.
=> Add workflow for Rustdocs

runtime/common/src/lib.rs, src/service.rs
Just want to be sure, we do not accidentally have changes in the core types of our client. Although, unlikely, wanted to have this in.
=> Use our own primitive types in the service

.github/ISSUE_TEMPLATE/issue_template.md, .github/PULL_REQUEST_TEMPLATE/pull_request_template.md
A first suggestion for using templates when opening new PRs or Issues. This is an attempt to remind developers to think about edge cases, thinking problems through, gathering feedback etc.
This shouldn't prevent PRs from being opened (quality gate), it is just so newcomers have an easier time contributing by having some guidelines, and to unify PR descriptions and issue descriptions.
Very happy to get feedback for adding/removing/rewording sections. That's just a first attempt!
=> Adding templates for PRs and Issues

pallets/anchors/src/lib.rs, pallets/anchors/src/tests.rs
Replace `Vec` storage with `BoundedVec` in `pallet-anchors` to be prepared for [Weights V2](https://github.com/paritytech/substrate/pull/10918)
Related to: #897
Modify `Vec` types found in the `pallet-anchors` storages.
```sh
cargo test -p pallet-anchors
cargo test --workspace --release --features test-benchmarks,try-runtime
cargo run --features runtime-benchmarks benchmark pallet --pallet="pallet-anchors" --chain="altair-dev" --extrinsic="*"
```
=> Pallet-anchors: replace Vec storage by BoundedVec

runtime/altair/src/lib.rs, runtime/development/src/lib.rs
The match statement that checks, if some account acting as a role is able to change the permissions storage is currently falsy allowing pool admins to change `Role::PermissionedCurrencyRole` entries. That is wrong. The PR fixes this. 
Non critical due to no permission currencies active in Altair. 
Fixes #986
See changes
=> Fix escalation of pool admin rights on currency roles

Cargo.lock, flake.nix, libs/primitives/src/lib.rs, pallets/bridge-mapping/Cargo.toml, pallets/bridge-mapping/src/lib.rs, pallets/bridge-mapping/src/mock.rs, pallets/nft/src/lib.rs, pallets/nft/src/mock.rs, pallets/nft/src/tests.rs, runtime/centrifuge/src/lib.rs, runtime/development/src/lib.rs
Adapt `pallet-nft` in order to use `pallet-fees`.
Fixes #959
- `pallet-nft` no longer uses its own mechanism to configure and pay fees.
- `pallet-bridge-mapping` no longer needs `pallet-nft` as dependency.
- `pallet-bridge-mapping` mock simplified.
```sh
cargo test -p pallet-nft
cargo test -p pallet-bridge-mapping
cargo test --workspace --release --features test-benchmarks,try-runtime
```
- *Should we notify somehow the new way of configuring fees for this pallet?*
=> pallet-nft using pallet-fees

pallets/loans/src/functions.rs, pallets/loans/src/lib.rs
Replace `Vec` storage with `BoundedVec` in `pallet-loans` to be prepared for [Weights V2](https://github.com/paritytech/substrate/pull/10918)
Related to: #897
Modify `Vec` types found in the `pallet-loans` storages.
```sh
cargo test -p pallet-loans
cargo test --workspace --release --features test-benchmarks,try-runtime
```
=> Pallet-loans: replace Vec storage by BoundedVec

pallets/loans/src/mock.rs, pallets/pools/src/benchmarking.rs, pallets/pools/src/lib.rs, pallets/pools/src/mock.rs, runtime/altair/src/lib.rs, runtime/development/src/lib.rs
Replace `Vec` storage with `BoundedVec` in `pallet-pools` to be prepared for [Weights V2](https://github.com/paritytech/substrate/pull/10918)
Related to: #897
Modify `Vec` types found in the `pallet-pools` storages.
```sh
cargo test -p pallet-pools
cargo test --workspace --release --features test-benchmarks,try-runtime
cargo run --features runtime-benchmarks benchmark pallet --pallet="pallet-pools" --chain="altair-dev" --extrinsic="*"
```
=> Pallet-pools: replace Vec storage by BoundedVec

.github/workflows/build-matrix.json, ci/script.sh
At this point one of Parity's libraries requires 1.62, so we can't stay on 1.60 any longer.
=> Bump srtool build to Rust 1.62

libs/traits/src/lib.rs
This PR adds `ensure_add` and `ensure_sub` trait methods to avoid being extremely verbose in math operations overflow checks, making the code more readable.
Before:
```rust
0u32.checked_sub(1).ok_or(ArithmeticError::Underflow)?;
```
After:
```rust
0u32.ensure_sub(1)?;
```
Addition of new ops traits into `libs/traits`
```rust
cargo test -p cfg-traits // Which will run the associated doc examples
```
=> Utility: add ensure_op trait methods to simplify overflow errors.

runtime/altair/src/lib.rs
This removes the migration from Altair, but leaves the code in the interest-accrual pallet. We _shouldn't_ ever need it again, but I don't want to rewrite the whole migration boilerplate for the next migration, so I'm leaving the dead code in place for now.
=> Remove accrual migration from Altair

pallets/loans/src/mock.rs, pallets/pools/src/lib.rs, pallets/pools/src/mock.rs, pallets/pools/src/tests.rs, pallets/pools/src/tranche.rs, runtime/altair/src/lib.rs, runtime/development/src/lib.rs
Currently, all of our native assets are described in `MultiLocation` as `X2(Parachain(_), GeneralKey(y))`. This works well for all assets with a static general key since we can _match_ on those static, const values. However, with Tranche tokens, as their general key is only obtained at runtime, we don't have a way of matching a MultiLocation representing a tranche apart from an exclusion-based approach.
Since we don't have tranche assets being used in production yet, hereby I suggest that we change the MultiLocation we use for tranche assets to be `X3(Parachain(x), PalletInstance(<pools_pallet_index>), GeneralKey(y))`, making it super easy to match on tranche tokens.
This comes particularly helpful in order to easily block transfers made through PolkadotXcm or XTokens that involve tranche …
=> pools: Add PalletIndex type

runtime/altair/src/lib.rs, runtime/altair/src/xcm.rs, runtime/centrifuge/src/lib.rs, runtime/centrifuge/src/xcm.rs, runtime/development/src/lib.rs, runtime/development/src/xcm.rs, runtime/integration-tests/src/xcm/kusama/restricted_calls.rs, runtime/integration-tests/src/xcm/kusama/tests/currency_id_convert.rs, runtime/integration-tests/src/xcm/polkadot/tests/currency_id_convert.rs, runtime/integration-tests/src/xcm/polkadot/tests/restricted_calls.rs
With the current `BaseCallFilter` set in all our runtimes, it is _not_ possible to build custom XCM message using `pallet_xcm` or `orml_xtokens` to transfer multiassets all together. We introduced this call filter to block all backdoors that would allow users to transfer Tranche tokens through XCM without the right permission checks. At the time we had no use case needing those calls in the first place, we just blocked them all. 
However, we now have an upcoming use case where to transfer xcUSDC tokens from Centrifuge to Moonbeam we will need either `transfer_multiassets` or `transfer_multiasset_with_fee`.
We now have more clarity surrounding how Tranche tokens will be transferred with permissions through Connectors, which won't make use of the common XCM fungibles config. Thus we can …
=> xcm: Support MultiAssets outbound transfers 

runtime/altair/src/lib.rs, runtime/centrifuge/src/lib.rs, runtime/development/src/lib.rs
Some PolkadotXcm extrinsics allow any user to prepare and send raw XCM messages which is undesired so we block those calls, leaving those only open for Root to execute.
=> runtime: Set sane BaseCallFilter

libs/traits/src/ops.rs
Improve the `cfg_traits::ops::ensure` module with more functionality.
Follows this work #1034
More support for the `ops::ensure` module:
- Added `EnsureFixedPointNumber` trait that adds `ensure_from_rational()`, `ensure_mul_int()` and `ensure_div_int()` for any `FixedPointNumber`.
- Added `EnsureInto` and `EnsureFrom` traits to check the overflow when numbers are converted.
- More accurate division error.
- Improve documentation.
- New feature (non-breaking change which adds *internal* functionality)
```sh
cargo test -p cfg-traits (run test in the examples)
cargo doc -p cfg-traits (check documentation links)
```
=> Ensure Ops extended

libs/types/src/fixed_point.rs
Adds fns for operations on fixed point numbers with fixed point operands with specified rounding preference to allow us to choose whether to use ceil or floor.
Fixes #931
Addition of ExtendedFixedNumber trait and implementation for Rate
Adds floor/ceil and with_rounding functions for:
- checked & saturating mul & mul int
- checked & saturating div and div int
- checked & saturating from rational
- checked reciprocal
- saturating pow
- [x ] New feature (non-breaking change which adds functionality)
Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration
=> Add fixed point custom rounding rate

pallets/pools/src/lib.rs, pallets/pools/src/tests.rs, pallets/pools/src/tranche.rs
Previsouly, the high-levl logic of creating a pool took care of ensuring that only a single residual tranche is used. The lower level logic on the `TrancheType` itself already allowed for this. This is misleading and lead to an error in some changes made on a feature branch. Hence, this cleans this up!
* Remove high level check for one residual tranche only
* Clean up tranche check logic
* Forbid residual after residual tranche in low level logic
Normal unit tests of pools cover this
=> Fix: Remove allowance of multi-residual tranches in low level api

runtime/centrifuge/Cargo.toml
The pipeline broke for the latest Polkadot upgrade (https://github.com/centrifuge/centrifuge-chain/actions/runs/3323478337/jobs/5493874232#step:7:1567). I added `pallet-collator-selection` to `std` for the `centrifuge` runtime, and this should fix the problem.
EXAMPLE change in the pools pallet EXAMPLE
EXAMPLE Updated the tests to fit the new pools pallet EXAMPLE
Locally, all tests run through.
=> Adding pallet-collator-selection to std for centrifuge runtime

pallets/liquidity-rewards/src/lib.rs, pallets/liquidity-rewards/src/mock.rs, pallets/liquidity-rewards/src/tests.rs, pallets/liquidity-rewards/src/weights.rs, pallets/rewards/src/lib.rs, pallets/rewards/src/mock.rs, pallets/rewards/src/tests.rs, runtime/development/src/lib.rs
Support different rewards for the same currency, adding a domain concept that splits the reward 
system.
This PR is a simpler implementation of https://github.com/centrifuge/centrifuge-chain/pull/1057 where de `rewards` traits are no modified.
- `pallet-rewards` and `pallet-liquidity-rewards` are now configured with a `DomainId` type.
=> Support for reward domains as currency prefixes

libs/primitives/src/lib.rs, runtime/altair/src/lib.rs, runtime/centrifuge/src/lib.rs, runtime/development/src/lib.rs
Syntactical change that ensures primitives is the location where we define our chain hashing and hash tyoe.
Fixes # (issue)
* Simple creation of new types
* Usage of new types in runtimes
=> Ensure streamlined hashing

README.md, libs/types/src/ids.rs, pallets/bridge/Cargo.toml, pallets/bridge/src/lib.rs, pallets/bridge/src/migration.rs, pallets/bridge/src/mock.rs, runtime/centrifuge/src/lib.rs, runtime/development/src/lib.rs
Fixes # (issue)
#1066 
Explained in the issue, the only additional info being that we had the runtime upgrade logic to centrifuge to have this pallet_bridge migration executed on the next runtime upgrade.
``` bash=
cargo build --release --features=try-runtime,runtime-benchmarks
RUST_LOG=runtime=trace,try-runtime::cli=trace,executor=trace ./target/release/centrifuge-chain try-runtime --execution Native --chain centrifuge-local --no-spec-name-check on-runtime-upgrade live --uri wss://fullnode.parachain.centrifuge.io:443
```
=> patch: fix inconsistent bridge accounts

libs/traits/src/lib.rs, libs/types/src/tokens.rs, pallets/pool-system/src/mock.rs, src/chain_spec.rs
We do two things here:
1. Implement `From` instead of `Into` for `TrancheCurrency` -> `CurrencyId
By implementing `From`, we get `into()` for free, whereas the opposite is not true. Note that this clippy also complains about this.
2. Drop `TrancheToken` that has been deprecated in favour of `TrancheCurrency`
=> cfg-types: Small touch on TokenCurrency + Drop TrancheToken

runtime/altair/src/lib.rs, runtime/centrifuge/src/lib.rs, runtime/development/src/lib.rs
This change adds an Aura timestamp check to the Timestamp::set pallet implementation.
=> Use Aura timestamp check

pallets/pool-registry/src/lib.rs, pallets/pool-system/src/impls.rs, pallets/pool-system/src/lib.rs, runtime/integration-tests/src/pools/pool_starts.rs, runtime/integration-tests/src/pools/utils/pools.rs
I adjusted the events for both `pool-registry` and `pool-system`, and renamed the `create` extrinsic in `pool-registry` to `register`.
* Added an enum `PoolRegistrationStatus` 
* Added a storage item `Pools`, which maps over `PoolId` and `PoolRegistrationStatus`
* Renamed the `create` extrinsic to `register`
* On each call to `register`, saving the `PoolId` of the new pool with the status `Registered`
* Emit `Registered` event with `PoolId` when pool is registered
* Remove not needed `MetadataSet` event
* Added `PoolCreated` event
* Emit `PoolCreated` event after a new pool is inserted in the `create()` function
=> Update pool events

pallets/liquidity-rewards/src/lib.rs, pallets/liquidity-rewards/src/mock.rs, runtime/development/src/lib.rs
Initially, a not configured epoch has a duration of 0 blocks. Currently, it is generating a NewEpoch event which it should not. This PR allows only to dispatch that event if the epoch has a duration.
```sh
cargo test -p pallet-liquidity-rewards
```
=> Rewards: Avoid first epoch event with zero duration

libs/primitives/Cargo.toml, libs/proofs/Cargo.toml, libs/types/Cargo.toml, pallets/anchors/Cargo.toml, pallets/bridge-mapping/Cargo.toml, pallets/collator-allowlist/Cargo.toml, pallets/connectors/Cargo.toml, pallets/fees/Cargo.toml, pallets/interest-accrual/Cargo.toml, pallets/keystore/Cargo.toml, pallets/liquidity-rewards/Cargo.toml, pallets/migration/Cargo.toml, pallets/nft-sales/Cargo.toml, pallets/pool-system/Cargo.toml, pallets/rewards/Cargo.toml
We fix the [package] data for the pool-system pallet and standardize all the 'repository' entries to point to
github.com/centrifuge/centrifuge-chain instead of suffixing the base url with the name of the pallet which currently results in a 404 and adds excessive and unnecessary noise to that entry.
=> cargo.toml: Fix and standardize [package] entries

Cargo.lock, Cargo.toml, flake.nix, libs/utils/Cargo.toml, libs/utils/src/lib.rs
We add this crate to place general utils that can be used across other pallets, runtimes, tests, etc.
To bootstrap it, we added and test a `vec_to_fixed_array` function that is used in https://github.com/centrifuge/centrifuge-chain/pull/1083
=> feat: Add cfg-utils crate

pallets/rewards/README.md, pallets/rewards/deferred_python_example.py, pallets/rewards/src/lib.rs
This pallet is supposed to use by other chains that needs a reward system.
Add a readme with the basic documentation about what this pallet is and how to use it.
Fixes #1093
- Added `README.md` to the crate
- Added a python example with the deferred reward implementation used by the [paper](https://centrifuge.hackmd.io/@Luis/SkB07jq8o).
-  Documentation update
=> Rewards: Add `pallet-rewards` documentation

pallets/pool-registry/src/lib.rs, pallets/pool-registry/src/mock.rs, pallets/pool-registry/src/tests.rs
Setting `metadata` of a pool also when `register`ing a new `pool` (inside `pallet-pool-registry`)
Fixes https://github.com/centrifuge/centrifuge-chain/issues/1096
Added the missing setter (and bound check) inside the `register` extrinsic for `pallet-pool-registry`. Added a test as well.
`cargo test --workspace --release --features test-benchmarks,try-runtime,runtime-benchmarks`
=> Bugfix set metadata

pallets/rewards/deferred_python_example.py, pallets/rewards/src/mechanism/deferred.rs
- Minor fix for the deferred mechanism to avoid sum overflow.
- The lost reward distribution is now added for the next epoch. This change is forced because adding the lost reward in the same epoch does not distribute the reward well for all participants.
*NOTE: This mechanism will be substituted for another mechanism that distributes the reward correctly even in cases when the reward is "lost" because of withdraws. The intention of this PR is to leave the mechanism finished without errors in the git history.*
=> Rewards: Fix for deferred mechanism

.github/workflows/benchmark.yml
Since there is no visible status for the `issue_comment` events, just added a comment at the beginning and at the end of the run for user feedback.
Here is an example of a successful run https://github.com/centrifuge/centrifuge-chain/actions/runs/3597875895 
You can find the zipped artifacts a the bottom of that page. There is no support to link the final artifact anywhere since the artifact_id is not available at the gh action level.
=> Testing Benchmark Job - Add status comments

docs/DEVELOPING.md
We improve and extend the docs on how to update to a new version of Polkadot.
The goal is to provided a better high-level description of the process and make the specific steps more explicit. We also extend it to cover the new `cargo patch` rules that also need to be updated in this context.
=> DEVELOPING: Improve docs on updating Polkadot

runtime/altair/src/lib.rs, runtime/centrifuge/src/lib.rs, runtime/development/src/lib.rs
Fixes weight proof size settings I had set incorrectly in upgrade.
- [x ] Bug fix (non-breaking change which fixes an issue)
- [ x] I have performed a self-review of my code
- [x ] My changes generate no new warnings
- [ x] New and existing unit tests pass locally with my changes
- [ x] I rebased on the latest `main` branch
=> Fix weight proof sizes

pallets/liquidity-rewards/src/benchmarking.rs
The addition of an initial epoch duration breaks the `liquidity-rewards` benchmarks for the development runtime. This PR fixes it.
Associated to https://github.com/centrifuge/centrifuge-chain/issues/1128
```sh
PARA_CHAIN_SPEC=development ./scripts/init.sh benchmark pallet-liquidity-rewards
```
=> Fixed liquidity-reward benchmarks

src/command.rs
When running the centrifuge-chain locally, if no `base-path` is provided to the relay chain args then a random temp directory is used which can cause inconsistent behavior such as the chain not producing blocks due to invalid/stale data in the db.
The changes in this PR aim at handling the case where `shared_params().base_path()` is a `Result(None)` which results in the behavior described above.
Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration
- Tested by running the chain locally and confirming that the `base_path` set in the init script is used for the relay chain.
=> relay-cli: Handle None case for shared base path

libs/traits/src/rewards.rs, pallets/liquidity-rewards/src/benchmarking.rs, pallets/liquidity-rewards/src/tests.rs, pallets/rewards/src/lib.rs, pallets/rewards/src/mechanism.rs, pallets/rewards/src/mechanism/base.rs, pallets/rewards/src/mechanism/deferred.rs, pallets/rewards/src/mechanism/gap.rs
Fixes #1140
- Add `is_ready()` method.
- Modify mock to support that.
```sh
cargo test -p cfg-traits
cargo test -p pallet-liquidity-rewards
```
=> Rewards: Implement distribution to groups with no stake

libs/primitives/Cargo.toml
A lack of std dependency avoids compiling some pallets individually, showing the following error:
```
error: cannot find macro `format` in this scope
--> /Users/luis/.cargo/git/checkouts/substrate-f4423eebfa0046a3/5ea6d95/primitives/authority-discovery/src/lib.rs:26:2
|
26 |     app_crypto!(sr25519, AUTHORITY_DISCOVERY);
|     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
|
= note: consider importing this macro:
scale_info::prelude::format
= note: this error originates in the macro `$crate::app_crypto_public_common_if_std` which comes from the expansion of the macro `app_crypto` (in Nightly builds, run with -Z macro-backtrace for more info)
error[E0433]: failed to resolve: use of undeclared crate or module `std`
...
```
This PR adds the lost feature to fix it
=> Fix individual compilation issue

.github/workflows/benchmark.yml, .github/workflows/docker.yml, .github/workflows/docs.yml, pallets/rewards/src/mechanism/gap.rs, pallets/rewards/src/tests.rs, pallets/rewards/src/tests/common.rs, pallets/rewards/src/tests/currency_movement.rs
This PR adds a complex test for the gap reward mechanism.
Fixes #1143
- Minor test constant renamed.
- Add a complex unitary test for this the gap mechanism:
```
A,B => Users
X,Y,Z,M => Currencies
Dx => Distributions
Gx => Groups
D0     |     D1    |          D2           |     D3    |    D4    |  D5
G1 -----------------------------------------------------------------------------
Stake X A | Stake Z A | MOVE Z ·              | Stake M A | MOVE X · |
|           |        ·              |           |        · |
|           |        v              |           |        v |
G2 -----------------------------------------------------------------------------
Stake Y B |           |         Unstake Z A/2 |           |          |
```
- Fix gap mechanism implementation with a movement issue found in …
=> Rewards: All-in test. Fix gap movement

libs/traits/src/ops.rs, libs/traits/src/rewards.rs, pallets/liquidity-rewards/src/lib.rs, pallets/rewards/src/mechanism/base.rs, pallets/rewards/src/mechanism/deferred.rs, pallets/rewards/src/mechanism/gap.rs
After merging the `ensure` module in Substrate, some minor things have changed from our current `ensure` module. This PR prepares our repo for a smooth upgrade.
The only required change to make it works is to substitute the import path `cfg_traits::ops` with `sp_arithmetic::traits`
- Refactor
```sh
cargo test -p cfg-traits
cargo test -p pallet-liquidity-rewards
```
=> Synchronize ensure module with Substrate

pallets/pool-system/src/impls.rs, pallets/pool-system/src/lib.rs
closes #1130
Updates the naming from pool-system events. 
* `PoolSystem::PoolCreated` -> `PoolSystem::Created`
* `PoolSystem::PoolUpdated` -> `PoolSystem::Updated`
This is needed before we release as this is hard to change afterwards in our indexing logic.
=> Change pool-system event names

pallets/loans/src/lib.rs
Add a table with the loan actions and requirements to the main `pallet-loan` docs. I think this can be helpful for a new reader of this pallet.
*I've already supposed the refactor done in #1155*
- Added documentation table
- Documentation
```sh
cargo doc -p pallet-loans
```
=> Add loan actions table documentation

src/chain_spec.rs, src/command.rs
Closes #1176 
- Adds Demo Chain Spec with a newly generated set of keys. 
- Simplifies the Development Spec to only use 1 collator
With these new keys, we will need to make sure that the provision environment script injects the session keys accordingly. @gpmayorga
=> Add Demo Spec

libs/traits/src/lib.rs, pallets/pool-system/src/impls.rs
By now, if all of you agree, implemented solution 3º of the issue.
Fixes #1185 
Adds `account_for` to get the account for a specific `pool_id` to the `PoolInspect` trait.
- Refactor
...
=> Add `account_for` to `PoolInspect` trait

pallets/liquidity-rewards/src/lib.rs, pallets/liquidity-rewards/src/mock.rs, pallets/liquidity-rewards/src/tests.rs
Fix the initial block issue.
Fixes #1191
- Remove the `System::block_number()` usage as a default storage value, because Substrate does not insert the value in the storage when the first value is fetched. This caused that each `get()` call returned the same current block number, and `on_initialize()` logic was never dispatched.
- Simplified generic usage.
- Minor docs additions.
- Adapt tests to catch the issue.
```sh
cargo test -p pallet-liquidity-rewards
```
=> Rewards: fix initial block value

libs/traits/src/rewards.rs, pallets/liquidity-rewards/src/benchmarking.rs, pallets/liquidity-rewards/src/tests.rs, pallets/rewards/src/lib.rs, pallets/rewards/src/tests.rs, pallets/rewards/src/tests/command_based.rs, pallets/rewards/src/tests/fuzzy.rs
This PR adds a basic fuzzy schema with the target of testing all possible combinations done in `pallet-rewards`.
Fixes #1184
Added a `fuzzy` module to create fuzzy tests.
- Modify the return type of distribution methods, in order to give more accurate information about what happens when it distributes. i.e be able to know the exactly minted reward. **The internal logic has no change.**
- `reward_group()` now returns the minted balance.
- Testing
- Internal API change (not external)
```sh
cargo test -p cfg-traits
cargo test -p pallet-liquidity
```
=> Added fuzzy test. Modified return type for distributions methods. 

runtime/development/src/lib.rs
In an effort to speed up the process of NFT minting in the POD, we would need to batch a couple of extrinsics. 
This change is meant to allow the POD operator to use the utility batch call on behalf of the identity that is minting the NFT.
Tested by running all the available test suites in the centrifuge POD.
=> proxy: Add utility pallet access to PodOperation proxy

libs/types/src/permissions.rs
Added `PODReadAccess` permission.
Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration
=> permissions: Add PODReadAccess permission

Cargo.toml, ci/script.sh, docs/DEVELOPING.md, libs/types/src/permissions.rs, pallets/pool-registry/Cargo.toml, pallets/pool-system/Cargo.toml, scripts/run_benchmark.sh, scripts/runtime_benchmarks.sh
`test-benchmarks` seems obsolete, and by testing with this feature instead of `runtime-benchmarks` we are not testing all crates with the correct `runtime-benchmarks`. 
[Slack thread](https://kflabs.slack.com/archives/C04GJQAM9P0/p1678197556596169)
- Removed occurrences of `test-benchmarks`.
- CI now runs `runtime-benchmarks` instead of `test-benchmarks`.
=> Remove `test-benchmarks` feature in favor of `runtime-benchmarks`

ci/script.sh, docs/DEVELOPING.md
- Remove `--release` in doc places where it is not really needed.
- Remove `--release` from integration tests.
- Remove `+nightly` from some docs because it seems not to be needed. The toolchain config should choose the right compiler channel.
Addition over https://github.com/centrifuge/centrifuge-chain/pull/1238
=> Build CI test in debug

runtime/development/src/lib.rs
For development environments sometimes test relay chains can halt producing blocks due to timing issues. In kubernetes for example, from time to time the infrastructure is restarted in an unhealthy way and this could leave the chain in a halt. 
To overcome this, usually a new relay chain is started and the parachain onboarded again from the last well known state. This will not work if the parachain expects that the relay chain block that has been imported is always incremented compare to the previous one, so changing the strategy here skips that check. 
Of course this is only acceptable in this test/dev environment case. 
This change makes recovering much easy, instead of having to rebuild a new wasm, export a new chain spec and add a block substitute for the latest finalized block in …
=> Skip relay block number check on dev runtime

.github/workflows/tests.yml, ci/script.sh, docs/DEVELOPING.md, pallets/loans/src/benchmarking.rs
Removes `--release` from our testing script for running unit tests. On my laptop this is 8 minutes faster. In CI where there is less parallelism, I expect that number to be larger.
Ran tests locally
=> Run unit tests in debug mode

.github/workflows/tests.yml, ci/script.sh, docs/DEVELOPING.md, pallets/loans/src/benchmarking.rs
This reverts commit cf83bc76e07992207f014dcc4021cb722cc58b83.
Reverts #1238, which is causing failures due to storage limitations in Github's CI runners.
Will be tested as part of this PR
=> Revert "Run unit tests in debug mode (#1238)"

.github/workflows/tests.yml
The Taplo task is already in the `Lints` job. We could alleviate the longer job around 5-7 min removing it from this.
Related issue: #1263
=> Remove taplo task from tests job

libs/traits/src/lib.rs, pallets/interest-accrual/src/lib.rs, pallets/interest-accrual/src/migrations.rs, pallets/interest-accrual/src/tests.rs, pallets/loans-ref/src/benchmarking.rs, pallets/loans-ref/src/lib.rs, pallets/loans-ref/src/tests.rs, pallets/loans-ref/src/types.rs, pallets/loans-ref/src/valuation.rs
Modify `InterestAccrual` to expose only an `interest_rate_per_year` parameter. No more interest rates per sec to handle. UI free from converting rates to show the correct yearly rates.
Fixes #1189
- The same storage is used. No migration is required for `interest-accrual`.
- The rate representation changes on the `pallet-loans` side, the type is the same but the value is stored diferently, so **it will require a migration if centrifuge release is launched before this**.
- This yearly simplification allows removing a couple of methods from `InterestAccrual` trait.
=> Interest accrual API only with yearly rates

libs/traits/src/lib.rs, pallets/interest-accrual/src/lib.rs, pallets/loans-ref/src/tests.rs, pallets/loans-ref/src/types.rs
Fixes #1203 
- `current_debt` and `previous_debt` merged into `calculate_debt`.
=> InterestAccrual: Unify current & previous debt methods

libs/traits/src/lib.rs, pallets/interest-accrual/src/lib.rs, pallets/loans-ref/src/tests.rs, pallets/loans-ref/src/types.rs
Adds again #1299 with a fast fix to avoid this issue: #1304
The fix consists in removing the `NotInPast` error completely, given the user the most updated debt in case `when` is one block in the "future".
**NOTE: The correct fix should be #1304**
=> Add again #1299 with fix

Cargo.lock, Cargo.toml, flake.nix, runtime/altair/Cargo.toml, runtime/altair/src/lib.rs, runtime/development/Cargo.toml, runtime/development/src/lib.rs
* Release commit for Altair `1026`
* Explicit migration type
* Release commit for Develop `1019`
* Fixes `SchedulerMigration`
Merge after: #1285 + #1299
=> Altair Release 1026 & Development Release 1019

.github/workflows/benchmark-check.yml, ci/script.sh, scripts/check_benchmarks.sh
This job does not generate weights, it only checks fastly for all runtimes if benchmarks work/compile.
You can test the script locally as follows for fast benchmark checks (it takes around 10-15s to check all runtime benchmarks once it's compiled):
```sh
./scripts/check_benchmarks.sh <runtime>
```
Being `<runtime>` the following possible values: `development`, `altair`, `centrifuge`
Fixes #1268
- New script
- New CI job
=> Add benchmark CI job for fast checks

.github/workflows/docker-nix.yml, ci/script.sh
* Disables docker nix build CI action which seems to be the root of our CI failing to push new docker images
* Bumps srtool to its latest version v1.66.1-0.9.25 from v1.64.0
=> ci: disable docker nix build

libs/mock-builder/Cargo.toml, libs/mock-builder/src/lib.rs, libs/mock-builder/src/location.rs, libs/mock-builder/src/storage.rs, libs/mock-builder/tests/pallet.rs
This PR gives to `mock-builder` the capability of mocking methods with generic bounds
Fixes #1316
- Added function identification with generics
- Fully refactorized to reduce macro usage and allows better organization
- Better error descriptions of what is going wrong.
- Added new tests
=> Mock-builder with generic methods support

pallets/restricted-tokens/src/lib.rs
With [this Ledger app ](https://polkadot.polkassembly.io/post/1795#rI1CzK92Mfp4llUpHAPj)on the horizion and in order to ease integration in the future, we want our `pallet-restricted-tokens` to stay as close as possible to `orml-tokens`. Hence, this PR switches the index of the extrinsics `transfer_all` and `transfer_keep_alive`.
* Change call index of `transfer_all` from `2` to `1`
* Change call index of `transfer_keep_alive` from `1` to `2`
=> Restricted-tokens: Sync call indicies with orml

libs/mocks/src/data.rs, libs/traits/src/data.rs, pallets/collection-data-feed/Cargo.toml, pallets/collection-data-feed/src/lib.rs, pallets/collection-data-feed/src/mock.rs, pallets/collection-data-feed/src/tests.rs
Minor changes over `collection-data-feed` to prepare it for the OracleValuation feature.
- Prices returned as `Result` instead of Option.
- `MockDataCollection` with user callback.
- Add license headers
- Clear unused features
=> CollectionDataFeed: Minor changes

.github/workflows/docs.yml, libs/mock-builder/src/lib.rs
This PR adds the main documentation with examples for understanding and using `mock-builder`.
=> mock-builder: Main documentation

pallets/loans-ref/src/lib.rs, pallets/loans-ref/src/loan.rs, pallets/loans-ref/src/tests.rs
This is a nitpicky change. But ideally, a `LoanId` should not belong to the `ActiveLoan` itself. A `LoanId` is an id used to identify such a loan, and should be handled at the pallet level, not at the loan level.
To rationale this, if instead of storing the `ActiveLoans` in a `Vec`, we would store it in a `StorageMap`, we should not place the `LoanId` in the `ActiveLoan` at the very beginning, as happen currently with `CreatedLoans` and `ClosedLoans`, so how we store the loans should not affect the data they hold.
=> Loans: LoanId out from ActiveLoan

pallets/loans-ref/src/benchmarking.rs, pallets/loans-ref/src/lib.rs, pallets/loans-ref/src/loan.rs, pallets/loans-ref/src/tests.rs, runtime/integration-tests/src/utils/loans.rs
- Added `unchecked_amount` in `repay()` extrinsic
- Added `total_repaid_unchecked` to `ActiveLoan` struct.
Fixes #1352
=> Loans: Add unchecked amount support

runtime/integration-tests/src/pools/pool_starts.rs, runtime/integration-tests/src/utils/env.rs
The logic previously fetched events at block zero, which where simply not existing as not populated. Substrate changed to panicking now, when somebody does this. This change fetches events only starting at block 1.
=> Fix: Failing integration tests

libs/mocks/src/data.rs, libs/traits/src/data.rs, pallets/data-collector/Cargo.toml, pallets/data-collector/src/lib.rs, pallets/loans-ref/src/benchmarking.rs, pallets/loans-ref/src/mock.rs, pallets/loans-ref/src/util.rs
- Added a `MaxCollectionSize` associated type that is only used under `runtime-benchmarks`.
By now, I think always using the maximum size of a price collection in benchmarks is ok. In comparison with the work done in `portfolio_valuation` over each `ActiveLoan`, deserializing once a small or a big vector of prices should not affect too much the final value.
If in the future, we need to struggle more with the benchmarks, we can add this as a variable parameter.
Associated to #1279
=> Loans: Support for benchmarking prices

pallets/loans-ref/src/benchmarking.rs, pallets/loans-ref/src/lib.rs, pallets/loans-ref/src/mock.rs, pallets/loans-ref/src/pricing/external.rs, pallets/loans-ref/src/tests.rs, pallets/loans-ref/src/util.rs, runtime/common/src/lib.rs, runtime/development/src/lib.rs
Although a price can be represented as a `Balance` or as a `Rate`, it seems a more appropriated and standardized way to do it as a `Rate`. This PR does the change.
=> Loans: Change price type from `Balance` to `Rate`

libs/types/src/permissions.rs, pallets/connectors/src/lib.rs, runtime/altair/src/lib.rs, runtime/centrifuge/src/lib.rs, runtime/development/src/lib.rs, runtime/integration-tests/src/utils/pools.rs, runtime/integration-tests/src/xcm/development/tests/connectors.rs
Closes https://github.com/centrifuge/centrifuge-chain/issues/1328
- Rename `MemberListAdmin` to `InvestorAdmin`  
- For all runtimes, extend the `InvestorAdmin` permissions to also include `PoolRole::PODReadAccess`.
=> Rename `MemberListAdmin` to `InvestorAdmin`

pallets/connectors/src/message.rs
=> connectors: Add new `Executed*` messages

pallets/investments/src/lib.rs
Fixes incorrect storage read of investment order id instead of the the redemption one during `do_collect_redeem`.
Not sure if it is sufficient to leave additional unit tests to the ones introduced in #1364 or whether we should try to bake this into the existing investments ones. I took a quick peek and did not have an immediate idea. AFAICS, we are testing investment and redemptions in the same scope which makes sense. This then might have lead to the investment id being higher than the `order.submitted_at()` such that `RedeemCollectedForNonClearedOrderId` does not happen: https://github.com/centrifuge/centrifuge-chain/blob/73609360c1c378a895c706dd42d9f480dfc6f987/pallets/investments/src/lib.rs#L826
When I tested this in isolation solely for redemptions in #1364, I could not get past the …
=> fix: order id storage in do_collect_redeem

libs/mock-builder/src/lib.rs, libs/mock-builder/src/storage.rs, libs/mock-builder/tests/pallet.rs
Now you can define mocks inside mock executions. It unlocks the set-get mock pattern, meaning you can return what you've previously set in another mock. In other words, you will always get the last you've set.
```rust
MyMock::mock_set(|value| MyMock::mock_get(move || value));
```
- Implementation
- Docs
- Tests
=> Mock builder: Support nested mock calls

pallets/loans/src/entities/loans.rs, pallets/loans/src/entities/pricing/external.rs, pallets/loans/src/tests/borrow_loan.rs, pallets/loans/src/tests/create_loan.rs, pallets/loans/src/tests/mod.rs, pallets/loans/src/tests/util.rs
Enable different max borrow models for external pricing
[slack thread](https://kflabs.slack.com/archives/C050E3ZN2JU/p1688037812005439)
=> Loans: unlimit external pricing borrows

Cargo.lock, libs/mocks/src/lib.rs, libs/mocks/src/time.rs, pallets/liquidity-rewards/Cargo.toml, pallets/liquidity-rewards/src/benchmarking.rs, pallets/liquidity-rewards/src/mock.rs, pallets/liquidity-rewards/src/tests.rs, pallets/rewards/src/mechanism/gap.rs, runtime/common/src/apis/rewards.rs, runtime/development/src/lib.rs, runtime/integration-tests/src/runtime_apis/rewards.rs
Fixes #1416 
- Replace `base` by `gap` mechanism (which requires instantiating a new pallet)
- Remove `pallet-timestamp` dependency from `pallet-rewards` using a mock.
=> Rewards: liquidity using gap & remove pallet-timestamp dependency

Cargo.lock, Cargo.toml, pallets/connectors-gateway/connectors-gateway-axelar-precompile/Cargo.toml, pallets/connectors-gateway/connectors-gateway-axelar-precompile/src/IAxelarForecallable.sol, pallets/connectors-gateway/connectors-gateway-axelar-precompile/src/IAxelarGateway.sol, pallets/connectors-gateway/connectors-gateway-axelar-precompile/src/IERC20.sol, pallets/connectors-gateway/connectors-gateway-axelar-precompile/src/lib.rs
Adding a precompile.
@cdamian this is my first approach for the precompile. LMKWYT. 
cc @branan
=> Pallet-Connectors-Gateway: Add Precompile for Axelar

pallets/loans/src/entities/loans.rs
Add `repayments_on_schedule_until` property to avoid future storage migrations required for https://github.com/centrifuge/centrifuge-chain/pull/1408/files.
=> Loans: Add `repayments_on_schedule_until` property

libs/mocks/src/pools.rs, libs/traits/src/lib.rs, pallets/connectors/src/inbound.rs, pallets/connectors/src/lib.rs, pallets/loans/src/benchmarking.rs, pallets/loans/src/entities/loans.rs, pallets/loans/src/entities/pricing/external.rs, pallets/loans/src/lib.rs, pallets/loans/src/migrations/nuke.rs, pallets/loans/src/tests/mock.rs, pallets/loans/src/util.rs, pallets/pool-system/src/impls.rs, pallets/pool-system/src/tests/mod.rs, runtime/altair/src/lib.rs, runtime/centrifuge/src/lib.rs, runtime/development/src/lib.rs
Addresses this bit of the Connectors v2 spec:
> Currently the trait PoolInspect also contains the get_tranche_token_price. A few arguments for refactoring
> 
> - Naming is misleading. Actually, it is computing the price
> - The trait should not be bloated. It is not inspecting here.
> - Implement something like trait TranchePricer or so
> - Maybe even store calculate prices, BUT NOT really sure if this is useful
Note: Leaving the last point since it's an optimisation that we don't need at the moment.
=> refactor: `TrancheTokenPrice` trait

libs/types/src/adjustments.rs, pallets/loans/src/benchmarking.rs, pallets/loans/src/entities/pricing/external.rs, pallets/loans/src/lib.rs, pallets/loans/src/tests/borrow_loan.rs, pallets/loans/src/tests/close_loan.rs, pallets/loans/src/tests/create_loan.rs, pallets/loans/src/tests/mock.rs, pallets/loans/src/tests/policy.rs, pallets/loans/src/tests/portfolio_valuation.rs, pallets/loans/src/tests/repay_loan.rs, pallets/loans/src/tests/write_off_loan.rs, runtime/altair/src/lib.rs, runtime/centrifuge/src/lib.rs, runtime/common/src/lib.rs, runtime/development/src/lib.rs
This change solves the issue, the complete Oracle support will be done in a new PR following the idea explained here: #1439 
Fixes #1447 
- Change Oracle prices from `Rate` to `Balance`.
- Change quantity from `Balance` to `Rate`. Currently, it's checked that only values with integer values are valid.
**NOTE: Labeled as migration, but it does not require migration if we purge the entire `pallet-loans`.**
=> Loans: oracle price as balance

pallets/loans/src/benchmarking.rs, pallets/loans/src/entities/loans.rs, pallets/loans/src/entities/pricing.rs, pallets/loans/src/entities/pricing/external.rs, pallets/loans/src/lib.rs, pallets/loans/src/tests/borrow_loan.rs, pallets/loans/src/tests/close_loan.rs, pallets/loans/src/tests/mod.rs, pallets/loans/src/tests/mutate_loan.rs, pallets/loans/src/tests/policy.rs, pallets/loans/src/tests/portfolio_valuation.rs, pallets/loans/src/tests/repay_loan.rs, pallets/loans/src/tests/util.rs, pallets/loans/src/tests/write_off_loan.rs, pallets/loans/src/types/mod.rs, runtime/integration-tests/src/utils/loans.rs
Jeroen's Slack introduction to this feature is [here](https://centrifugedao.slack.com/archives/C05DX0RH1T3/p1688128534804769)
Basically, we want to write the principal in different ways depending on the pricing method. As a schema, instead of always given a `Balance` as principal in `borrow()` and `repay()` methods, we want:
```rust
enum Principal {
Internal {
amount: Balance
},
External {
quantity: Rate,
settlement_price: Balance,
}
}
```
The core idea is that for external pricing, the amount that is transferred to the pool is `quantity * settlement_price`, and the `outstanding_quantity` is reduced by `quantity`.
So, with this schema:
- Amount transferred: `quantity * settlement_price`
- Amount used for calculating interest: `quantity * notional`
- Amount used for valuating the loan: …
=> Loans: borrow & repay method using pricing-based principal

runtime/common/src/lib.rs, runtime/development/src/lib.rs
Another solution for #1466 that it does not imply changes in deployment/scripts.
- Add a `RuntimeChange` wrapper that modifies delay times for "fast" runtime versions. Each runtime can choose between using `RuntimeChange` or `fast::RuntimeChange` depending on their configuration.
=> Runtime: add `RuntimeChange` version for fast runtimes

Cargo.lock, Cargo.toml, libs/primitives/src/lib.rs, libs/traits/src/ethereum.rs, libs/traits/src/lib.rs, pallets/ethereum-transaction/Cargo.toml, pallets/ethereum-transaction/src/lib.rs, pallets/ethereum-transaction/src/mock.rs, pallets/ethereum-transaction/src/tests.rs, runtime/development/Cargo.toml, runtime/development/src/evm.rs, runtime/development/src/lib.rs, runtime/integration-tests/Cargo.toml, runtime/integration-tests/src/ethereum_transaction/mod.rs, runtime/integration-tests/src/ethereum_transaction/pallet.rs, runtime/integration-tests/src/lib.rs, runtime/integration-tests/src/utils/env.rs, runtime/integration-tests/src/utils/evm.rs, runtime/integration-tests/src/utils/mod.rs
Part 2 of - https://github.com/centrifuge/centrifuge-chain/pull/1376
The pallet added in this PR will be used by the Axelar EVM gateway router which will be added in a following PR.
An example of how this pallet is used can be found [here](https://github.com/centrifuge/centrifuge-chain/blob/8d9dd50a0e580740c33718b18c8accb6de4eb539/pallets/connectors-gateway/connectors-gateway-routers/src/axelar_evm.rs#L136) 
- Add Ethereum Transaction pallet
=> connectors-gateway: Add Ethereum Transaction pallet

runtime/altair/src/lib.rs, runtime/centrifuge/src/lib.rs, runtime/development/src/lib.rs
Related to #1461 
This PR adds the missing loans extrinsic to `ProxyType` for all runtimes.
I've seen that `ProxyType::NonTransfer` for centrifuge runtime is not configured with the pool/loan/permission pallets. Is this deliberate, or did we miss this from the last release? @branan @wischli
=> Update ProxyType for runtimes

res/algol-spec.json
The intent for Algol was that it would be like Catalyst:
* parachain ID == Altair ID
* EVM chain ID == (Altair ID) + 1
Due to a typo (or a bad copy and paste), the parachain ID ended up equal to the EVM chain ID.
=> Fix Algol parachain ID

pallets/loans/src/entities/loans.rs, pallets/loans/src/entities/pricing/external.rs, pallets/loans/src/entities/pricing/internal.rs
~~Add `outstanding_debt` loan's property to runtime API~~
Add `outstanding_principal` and `outstanding_interest` to the runtime API.
=> Loans: add outstanding principal & interest to runtime API

src/command.rs
Identifycation of path based specs is based in the `id` string. We did not adapt our matching case for `algol` and it is wrongly identified as `Development` then, making the start-up fail.
=> fix: identifying algol chain correctly

pallets/loans/src/entities/loans.rs, pallets/loans/src/tests/borrow_loan.rs, pallets/loans/src/tests/repay_loan.rs
Minor loans changes.
- `ClosedLoans` contains the split repaid amounts instead of the total.
- Extra: Add extra checks for present value in external pricing
=> Loans: close with repays amount

pallets/interest-accrual/src/lib.rs, runtime/altair/src/lib.rs, runtime/altair/src/migrations.rs, runtime/centrifuge/src/lib.rs, runtime/centrifuge/src/migrations.rs, runtime/development/src/lib.rs, src/chain_spec.rs
Fixes #1461
- Nuke migration for `pallet-loans`
- Tested in `altair` and `centrifuge`, and currently, there is nothing there. **Should we then add the migration?** I think it makes sense to remove anything anyone can add these days there until the next release.
- Nuke migration for `interest-accrual`
- I removed the old `StorageVersion` storage in order to use the new one.
- Found some rates that we can delete.
## Tests
Comand: 
```sh
RUST_LOG=runtime=trace,try-runtime::cli=trace,executor=trace cargo run --release --features try-runtime try-runtime --runtime target/release/wbuild/altair-runtime/altair_runtime.wasm --chain centrifuge on-runtime-upgrade live --uri wss://fullnode.altair.centrifuge.io:443
```
Output:
```
2023-08-17 16:38:24.490  INFO main runtime_common::migrations::nuke: …
```
=> Add nuke migration for loans & interest-accrual

runtime/altair/src/lib.rs, runtime/altair/src/migrations.rs, src/chain_spec.rs
This PR adds:
- A migration to fund the distributed reward account with `ED`.
- Enable liquidity rewards for all chains based on `altair`. After this [slack conversation](https://kflabs.slack.com/archives/C04H9H7EVEE/p1692286840844139) resolution
=> Rewards: Add deposit for reward account for Altair. Enable liquidity rewards for all chains based on Altair

runtime/altair/src/lib.rs, runtime/centrifuge/src/lib.rs
The `estimate_gas` RPC uses the same pathway as a `call` RPC, so we need to allow contract creation in this path so that `estimate_gas` of contract creation will work.
This does not affect any allow/deny-listing of actual contract creation, since that filtering will happen on the transaction itself rather than the `estimate_gas` call.
=> Allow `estimate_gas` for contract creation

.github/workflows/build.yml
We cut a release for `Altair 1030 for Algol`, I realised after an `Unauthorised` runtime upgrade attempt, that we don't publish the `Algol` wasm runtime to GCS. 
So what I used for my attempted runtime upgrade was the output wasm of `build-runtime-fast` for Altair instead.
Here we do handle the `Publish to GCS` job for `target == 'build-runtime-testnet' && package == 'altair-runtime'`; in other words, for `Algol`. I also named the wasm stored on GCS `algol-{hash}` to avoid having multiple names to address it by and have it in different directories, etc.
=> ci: Publish Algol wasm to GCS

.github/workflows/build.yml
Syntax fixup for https://github.com/centrifuge/centrifuge-chain/actions/runs/5947693754/workflow#L76.
✅  Installed and ran [actionlint](https://github.com/rhysd/actionlint/tree/main) locally to make sure this issue is resolved
=> ci: Fix build.yaml syntax

pallets/loans/docs/types.md, pallets/loans/src/entities/loans.rs, pallets/loans/src/entities/pricing/external.rs, pallets/loans/src/lib.rs, pallets/loans/src/tests/borrow_loan.rs, pallets/loans/src/tests/mock.rs, pallets/loans/src/tests/portfolio_valuation.rs, pallets/loans/src/tests/repay_loan.rs, pallets/loans/src/types/mod.rs
Adds behaviour that external assets can use latest settlement price instead of the oracle price, if no price has been fed. Also adds a borrow restriction that blocks this behaviour.
=> Use latest settlement price by default

Cargo.lock, runtime/centrifuge/Cargo.toml, runtime/centrifuge/src/lib.rs, runtime/centrifuge/src/migrations.rs, runtime/centrifuge/src/weights/mod.rs, runtime/centrifuge/src/weights/pallet_liquidity_rewards.rs, src/chain_spec.rs
- Liquidity reward pallets to centrifuge runtime.
- Added a migration to fund the distributed reward account with ED.
=> LiquidityRewards: support for centrifuge runtime

Cargo.lock, runtime/altair/src/migrations.rs, runtime/centrifuge/Cargo.toml, runtime/centrifuge/src/evm.rs, runtime/centrifuge/src/lib.rs, runtime/centrifuge/src/migrations.rs, runtime/centrifuge/src/xcm.rs, runtime/common/src/evm/precompile.rs
Adding the Liquidity Pools pallets to the centrifuge runtime.
- NOTE - No event being triggered at the moment
- NOT use LPs as InboundQueue
- Only allow (`AddCurrency`, `UpdateMember`, `AddPool`, `AddTranche`, `UpdateTrancheTokenPrice`)
- Uses gateway as real outbound
=> Add Liquidity Pools related pallets to centrifuge runtime

runtime/centrifuge/src/lib.rs, runtime/centrifuge/src/xcm.rs
The changes in this PR are some of the follow-ups needed after adding the LP related pallets, specifically:
- enable the LP gateway XCM origin converter
- use `Quantity` instead of `Rate` in the LP pallet config
=> Upgrade1020 LP follow-ups

Cargo.lock, libs/primitives/Cargo.toml, libs/primitives/src/lib.rs, runtime/altair/src/migrations.rs, runtime/altair/src/xcm.rs, runtime/centrifuge/src/lib.rs, runtime/centrifuge/src/migrations.rs, runtime/centrifuge/src/xcm.rs, src/chain_spec.rs
For both the Centrifuge as well as the Altair runtimes adds:
* Migration to set safe XCM version for Centrifuge and Altair chains to v2 (mirroring behaviour of relay and other parachains)
* `pallet_liquidity_pools_gateway::Call::process_msg` to `SafeCallFilter` which enables this to be executed by xcm `transact`
=> feat: safe XCM version migration + extend SafeCallFilter

pallets/liquidity-pools/src/lib.rs, runtime/altair/src/lib.rs, runtime/centrifuge/src/lib.rs, runtime/development/src/lib.rs
We forgot to remove these when we introduced the new gateway, deleting them here. No storage migrations needed.
=> liquidityPools: Clean up orphan storage and events

.github/workflows/lints.yml, Cargo.lock
Taplo is suddenly failing to compile when installed on the CI but also locally. This is a commodity and we don't _need_ this job on the CI, particularly in a phase as we are in with lots of work to get in.
Removing the job for now.
=> ci: Disable taplo

runtime/altair/src/lib.rs, runtime/centrifuge/src/lib.rs, runtime/development/src/lib.rs
After #1520 we missed updating the type for runtime APIs. This PR fixes it.
It's not a critical bug because the logic/state/extrinsic are not affected by this. Just the result obtained in the API has more "zeros" than expected.
=> Fix rate type used in RuntimeAPIs for pools

pallets/order-book/src/benchmarking.rs, pallets/order-book/src/mock.rs, pallets/order-book/src/tests.rs, runtime/development/src/lib.rs
Ideally, `order-book` should use an 18-decimal fixed point number too.
- Change type in dev runtime.
- Remove dependency from `Rate` type in tests/benchs.
=> OrderBook: Use ratio instead of rate

Cargo.lock, pallets/liquidity-pools-gateway/routers/src/routers/axelar_evm.rs, runtime/development/Cargo.toml, runtime/development/src/lib.rs
Dropping the explicit call to the LP contract since our testing revealed that it is unnecessary.
=> routers: Drop LP contract call from Axelar message

Cargo.lock, libs/mocks/src/liquidity_pools.rs, libs/utils/Cargo.toml, libs/utils/src/lib.rs, pallets/liquidity-pools-gateway/Cargo.toml, pallets/liquidity-pools-gateway/axelar-gateway-precompile/Cargo.toml, pallets/liquidity-pools-gateway/axelar-gateway-precompile/src/lib.rs, pallets/liquidity-pools-gateway/routers/Cargo.toml, pallets/liquidity-pools-gateway/src/lib.rs, pallets/liquidity-pools-gateway/src/mock.rs, pallets/liquidity-pools-gateway/src/tests.rs, runtime/altair/src/lib.rs, runtime/development/Cargo.toml, runtime/development/src/lib.rs, runtime/development/src/liquidity_pools.rs, runtime/development/src/xcm.rs, rustfmt.toml
The address that we are receiving from EVM chains is a `utf-8(hex(address))` encoded byte bloob. This was an issue before because we expected it to be just an `[u8; 20]`.
* update parsing of account from Axelar
* utility function for both precompile and gateway
=> feat: encode source address correctly in gateway

Cargo.lock, runtime/altair/Cargo.toml, runtime/altair/src/lib.rs, runtime/altair/src/migrations.rs
Simply bumps `altair` spec version to 1033 such that we can update Algol to latest `main` state.
=> chore: Algol 1033

scripts/check_benchmarks.sh
* Enables checking a single pallet's benchmark via the `check_benchmark.sh` script
```bash
scripts/check_benchmarks.sh $runtime $pallet
```
```bash
scripts/check_benchmarks.sh $runtime
```
=> feat: support single pallet check benchmark

libs/traits/src/investments.rs, libs/types/src/investments.rs, pallets/foreign-investments/src/errors.rs, pallets/foreign-investments/src/impls/mod.rs, pallets/foreign-investments/src/lib.rs, pallets/liquidity-pools/src/hooks.rs, pallets/liquidity-pools/src/inbound.rs, pallets/liquidity-pools/src/lib.rs, pallets/liquidity-pools/src/message.rs, runtime/altair/src/lib.rs, runtime/centrifuge/src/lib.rs, runtime/development/src/lib.rs, runtime/integration-tests/src/liquidity_pools/pallet/development/tests/liquidity_pools/add_allow_upgrade.rs, runtime/integration-tests/src/liquidity_pools/pallet/development/tests/liquidity_pools/foreign_investments.rs
* Adds `InvestmentPaymentCurrency` storage for the `foreign payment currency` upon receiving the first IncreaseInvestOrder message (similar to redemptions)
* `InvestmentPaymentCurrency` will be cleared if the `InvestState` is cleared, i.e. if neither an unprocessed swap nor investment is happening in case of reaching `NoState` or `SwapIntoForeignDone`
* `InvestmentPaymentCurrency` will be overwritten upon receiving `IncreaseInvestOrder` or `CollectInvestOrder` to be less restrictive to investors
* We will read from that storage after the investment was collected through `pallet_investments::collect_invest_for` such that the dispatch of `ExecutedCollectInvest` happens automatically
* This enables us to not have to add a `collect_foreign_investment_for` extrinsic.
* For collecting …
=> feat: enable full foreign collect flow via extrinsic

libs/mocks/src/pools.rs, libs/traits/src/benchmarking.rs, libs/traits/src/lib.rs, pallets/loans/src/benchmarking.rs, pallets/loans/src/tests/mock.rs, pallets/order-book/src/benchmarking.rs, pallets/order-book/src/lib.rs, pallets/pool-system/src/impls.rs, pallets/pool-system/src/tests/mod.rs
Adds an benchmark helper to the `pallet-order-book` which exposes the necessary setup to register a trading pair for arbitrary currencies. 
It is inspired by the the existing `PoolBenchmarkHelper` which was moved to a new `benchmarking` module of `cfg_traits`.
Required for benchmarking LPs, especially foreign investments
=> feat: orderbook bench helper

pallets/loans/src/lib.rs, pallets/loans/src/types/portfolio.rs
Optional addition: I think it could be beneficial to leave the portfolio values representing the exact loans found in `ActiveLoans`. Anyways, the storage is reset for each NAV computation, but having during some time different elements in the portfolio and active loans could lead to errors.
PROS: Data more structured.
CONS: 1 read/write DB for `close_loan()` action.
- add `portfolio.remove_elem()`
- add Unitary tests to the portfolio module.
=> Loans: Remove portfolio entry when removing a loan +  portfolio UT

libs/types/src/tokens.rs, pallets/investments/src/lib.rs, runtime/centrifuge/src/migrations.rs
We want to migrate the `currency` of the `Anemoy` pool from `LpEthUSDC` to (Polkadot-native) `USDC` on Centrifuge.
- Anemoy has pool id 4,139,607,887 (the only pool currently registered on Centrifuge)
- We will migrate the currency of that pool from `ForeignAsset(100,001)` (`LpEthUSDC`) to `ForeignAsset(6)`  (`Circle’s USDC native on Polkadot`)
- Both currencies have 6 decimals so no extra considerations in that regard
=> centrifuge: Anemoy pool currency migration

libs/mocks/src/pools.rs, libs/test-utils/src/mocks/accountant.rs, libs/types/src/tokens.rs, pallets/investments/src/benchmarking.rs, pallets/investments/src/lib.rs, pallets/investments/src/mock.rs, pallets/investments/src/tests.rs, pallets/investments/src/weights.rs, runtime/altair/src/lib.rs, runtime/altair/src/weights/mod.rs, runtime/altair/src/weights/pallet_investments.rs, runtime/centrifuge/src/lib.rs, runtime/centrifuge/src/weights/mod.rs, runtime/centrifuge/src/weights/pallet_investments.rs, runtime/development/src/lib.rs
Fixes #918
- `update_invest_order()` &
- `update_invest_redeem()`:
- `94_000_000 + reads(8) + writes(4)`
- `collect_investments()` &
- `collect_investments_for()` &
- `collect_redemptions()` &
- `collect_redemptions_for()`:
- `97_000_000 + 4_000_000 * N + reads(7) + reads(1) * N + writes(3)`
=> Investments: benchmarks

libs/mock-builder/src/lib.rs
Fix the link issue.
Because the test code can not be attached from rust docs, I've linked directly to the file in `foss3` repo.
Done also in `foss3` copy of `mock-builder`
=> MockBuilder: fix doc link

libs/mocks/src/token_swaps.rs, libs/traits/src/lib.rs, pallets/foreign-investments/src/hooks.rs, pallets/foreign-investments/src/impls/mod.rs, pallets/foreign-investments/src/lib.rs, pallets/foreign-investments/src/tests.rs, pallets/order-book/src/benchmarking.rs, pallets/order-book/src/lib.rs, pallets/order-book/src/mock.rs, pallets/order-book/src/tests.rs, runtime/altair/src/lib.rs, runtime/centrifuge/src/lib.rs, runtime/common/src/lib.rs, runtime/development/src/lib.rs, runtime/integration-tests/src/liquidity_pools/pallet/development/tests/liquidity_pools/foreign_investments.rs
This PR mainly fixes issues for partial orderbook fulfillments of foreign investments as a successor of #1559. It also enables partial investments for orders created via extrinsics:
* Fixes issues for partial swap order fulfillments in `pallet-foreign-investments`
* Enables partial swaps for orders created through user extrinsics `pallet_order_book::create_order` and `pallet_order_book::user_update_order` which had the `min_fulfillment_amount` set to the `buy_amount` making partial fulfillments impossible
* Removes `min_fulfillment_amount` from `TokenSwaps` trait
* IMO, it should solely be handled by the orderbook
* Adds `NativeBalanceDecimalConverter` which provides means of converting between native and asset balance (i.e. re-denomination)
* Adds `MinFulfillmentAmountNative` to …
=> fix: min fulfillment amount for partial fulfillment

libs/test-utils/src/mocks/accountant.rs, libs/test-utils/src/mocks/order_manager.rs, libs/traits/src/investments.rs, libs/types/src/investments.rs, pallets/investments/src/benchmarking.rs, pallets/investments/src/lib.rs, pallets/investments/src/mock.rs, pallets/pool-registry/src/benchmarking.rs, pallets/pool-system/src/benchmarking.rs
Some simplifications regarding investment info/properties. [Slack conversation](https://kflabs.slack.com/archives/C04GJQAM9P0/p1695383388075129)
- Removed the `InvestmentProperties` trait. Now, the type `InvestmentInfo` is used directly (which I think simplifies some parts)
- Removed the need for the `where` bound everywhere the investment pallets is used to determine the correct `InvestmentInfo` (this simplifies things for future integration tests)
=> Investments: simplify constraints and remove InvestmentProperties trait

pallets/foreign-investments/src/impls/benchmark_utils.rs
Fixes benchmarking CI after merging #1570 unwantedly before the entire CI finished (benches were still progressing, suppose those are optional which I was not aware of). Sorry about the inconvenience!
=> fix: foreign investments bench

.github/CODEOWNERS, .github/issue_template.md, .github/pull_request_template.md
- Removed `*.toml` matching to avoid having all of us in all PRs.
- (opinionated) Removed more template sections. I think most of all, do not use those sections, and in a lot of cases, it does not apply to the issue/PR purpose, and it only puts another mind barrier to open new issues. I think open issues should be something fast/easy/kind to incentivize tracking our task.
=> Github codeowners/templates changes

runtime/development/src/lib.rs, runtime/development/src/migrations.rs
* Adds precompile migration from #1580 to development runtime required for `Demo` environment
=> feat: add precompile migration to dev

Cargo.lock, runtime/altair/src/migrations.rs, runtime/centrifuge/Cargo.toml, runtime/centrifuge/src/lib.rs, runtime/centrifuge/src/migrations.rs, runtime/common/src/migrations/precompile_account_codes.rs, runtime/development/Cargo.toml, runtime/development/src/lib.rs, runtime/development/src/migrations.rs
Removes `spec_version` checks for Anemoy, USDC and EVM Precompile Accountcode migrations. 
Apparently, we cannot rely on the result of `try-runtime` which [succeeded for all these migrations](https://github.com/centrifuge/centrifuge-chain/pull/1580#issuecomment-1747015476). However, in practice neither Dev/Demo nor Catalyst ran the EVM Accountcode migrations (Anemoy & USDC migrations ran on Catalyst in a previous upgrade from 1020 to 1021). My understanding is that at the time of executing `on_runtime_upgrade()`, the spec_version has been bumped already and `LastRuntimeUpgrade` updated to the current `spec_version`. I could not find any way of reading the pre upgrade spec_version.
None of the migrations performs many reads or writes. Moreover, they were adjusted such that no written …
=> fix: remove spec_version check for Centrifuge 1023 migrations

runtime/altair/src/migrations.rs, runtime/common/Cargo.toml, runtime/common/src/migrations/asset_registry_xcmv3.rs
The check for the expected state of `asset_registry` migration is checked under `try-runtime`, if the chain state changes, the new state sets an empty vector, removing all currencies.
This PR modifies the migration only to take effect if the chain state is the expected state.
=> AssetRegistry: protect asset_registry migration

Cargo.toml, pallets/liquidity-pools/src/lib.rs, pallets/liquidity-pools/src/message.rs, runtime/common/Cargo.toml, runtime/integration-tests/Cargo.toml
After a discussion within the `MultiChain` team, we agreed that we need to include the timestamp at which a tranche token price was calculated in the `UpdateTrancheToken` message.
Given that we add this new field at the end of the message, no migrations or special handing is necessary since this will make this messages backwards and forwards compatible.
=> lp: Add `compute_at` to `UpdateTrancheTokenPrice`

libs/mocks/src/data.rs, libs/test-utils/src/mocks/accountant.rs, pallets/block-rewards/src/tests.rs, pallets/loans/src/benchmarking.rs
Fixes over the main polkadot-v0.9.43 branch
=> Polkadot v0.9.43: Loan and investment benchmarks fixed

pallets/liquidity-pools/src/lib.rs, pallets/liquidity-pools/src/message.rs
When adding a tranche token to a LP-compatible domain, we now need to specify which implementation of the `RestrictionManager` we want to use on a per-tranche-token basis. For that, we add this new field that serves as an identifier that will be picked up on the destination accordingly.
=> LiquidityPools: Add `restriction_set` field to `AddTranche` message

pallets/pool-system/src/impls.rs, pallets/pool-system/src/tests/mod.rs, runtime/common/src/lib.rs
Issuers need to have the possibility to transfer debt between loans without restrictions. In the future we might add restrictions back, but based on a per pool setup, so investors know for each pool what to expect.
Fixes issues that our issuers are having.
Furthermore, this change allows to deterministically derive a `ChangeId` for a given proposed change, as we exclude the time of submission from the hash. This means, that equal changes will overwrite past onces, but that is fine as it just means we are extending the time of execution for that change.
* `ChangeId` now `Blake256(Change)`
* `Change::TransferDebt` has no restrictions
=> Fix: Transfer debt

Cargo.lock, Cargo.toml
Right now, our Substrate client supports `rocksdb, paritydb, auto` as database types. The frontier backend inherits the database type from that CLI. When [Frontier upgraded to Polkadot v0.9.42](https://github.com/paritytech/frontier/pull/1054), the `rocksdb` feature was added to the `fc-db` crate. Since we did not opt into that feature, our client is throwing when attempting to use `rocksdb` as db.
* Adds `rocksdb` feature to `sc-cli`, `sc-service`, `fc-db` and `frame-benchmarking-cli` crates
* Fixes issue of unsupported rocksdb for frontier backend
```
Error: Service(Other("Supported db sources: `auto` | `rocksdb` | `paritydb`"))
```
```bash
cargo run -r \
--chain="development" \
--tmp \
--parachain-id="2000" \
--wasm-execution=compiled \
--execution=wasm \
--rpc-external \
--rpc-cors …
```
=> fix: enable rocksdb for frontier backend

.github/workflows/build-docker.yml, docker/centrifuge-chain/Dockerfile
Removing some unnecessary lines on the Docker file and making everything more explicit
=> Dockerfile review after CI changes

libs/traits/src/lib.rs, libs/types/src/fee_keys.rs, runtime/common/src/fees.rs
The current API provided by the traits around `pallet_fees` to handle fees has two negative points:
1. In order to use it in a pallet you need to use at least 2 associated types in the `Config` trait. i.e:
```rust
/// Entity used to pay fees
type Fees: Fees<AccountId = Self::AccountId>;
/// Key used to get the fee value.
type ActionAFeeKey: Get<<Self::Fees as Fees>::FeeKey>;
```
2. The knowledge of how to consume that fee is in the pallet when the pallet should not be aware of it. This should be a runtime concern.
```rust
/// Inside the pallet we decide when we should not do that
T::Fees::fee_to_treasury(&who, Fee::Key(T::ActionAFeeKey))?;
// or
T::Fees::fee_to_author(&who, Fee::Balance(T::ActionAFeeValue))?;
```
We can fix these 2 points by coding the whole fee action in different types …
=> Fees API Improvement

.dockerignore, .github/dependabot.yml, .github/workflows/build-docker.yml, docker/centrifuge-chain/Dockerfile, docker/scripts/entrypoint.sh
Includes:
- Polkadot relays now expect their folder to be named "polkadot" rather than "relay-chain". The new docker container is made aware of this and will rename the folder if needed.
- Dockerfile build based on Parity "rust-ready" production base image
- More lean Dockerfile
=> Docker: solve polkadot relay folder renaming and other small fixes

runtime/common/src/changes.rs, runtime/common/src/lib.rs, runtime/development/src/lib.rs
Currently, adding a new change to `RuntimeChange` implies a lot of boilerplate. With `From/TryInto` methods and duplicate the work for `fast::RuntimeChange` version. This PR tries to ease the process.
- Added a macro to add new `From/TryInto` methods
- `fast::RuntimeChange` type has benn removed, and now `RuntimeChange` allows itself to be parameterized with an `Options` type that gives it a specific behavior, i.e. a fast version of `RuntimeChange`.
- Moved to its own `changes` module.
- https://github.com/centrifuge/centrifuge-chain/pull/1633
- https://github.com/centrifuge/centrifuge-chain/pull/1629
=> Modify `RuntimeChange` to support easily new additions

docker/docker-compose-local-chain.yml, docker/docker-compose-local-relay.yml, scripts/init.sh
* Fixes `docker-compose` files and usage after moving files and updating Dockerfile in #1611 
* Runs docker-compose containers as `root` user
```
PARA_DOCKER_IMAGE_TAG=latestmain-8b9c8f0-23-11-23 PARA_DOCKER_PROFILE=default DOCKER_ONBOARD=true PARA_CHAIN_SPEC=development ./scripts/onboard.sh
```
onboard.shj
```
cc_docker_image_tag="${PARA_DOCKER_IMAGE_TAG:-test-main-latest}"
parachain_spec="${PARA_CHAIN_SPEC:-centrifuge-local}"
parachain_method="${PARA_METHOD:-docker}"
export PARA_DOCKER_IMAGE_TAG=$cc_docker_image_tag
export CC_DOCKER_TAG=$cc_docker_image_tag
export PARA_CHAIN_SPEC=$parachain_spec
if [[ $parachain_method == "docker" ]];
then
export DOCKER_ONBOARD=true
fi
./scripts/init.sh stop-relay-chain
./scripts/init.sh start-relay-chain
if [[ $parachain_method == "docker" ]];
then …
```
=> fix: docker-compose

runtime/common/src/changes.rs
The version of `RuntimeChange` with the `FastDelay` option was not the special case required for benchmarking
[slack thread](https://kflabs.slack.com/archives/C04GJQAM9P0/p1701440777599979)
=> Fix benchmark issue in development

.github/workflows/build-docker.yml
The docker build is intented to be triggered for 
* Pushes onto `main`
* Release drafts (saved without publishing or saved with publish independent of the release type)
Right now, the release part triggers on unpublishing an existing release.
Aggregated from https://docs.github.com/en/webhooks/webhook-events-and-payloads#webhook-payload-object-35
> * published: a release, pre-release, or draft of a release is published
> * unpublished: a release or pre-release is deleted
> * created: a draft is saved, or a release or pre-release is published without previously being saved as a draft
> * edited: a release, pre-release, or draft release is edited
> * deleted: a release, pre-release, or draft release is deleted
> * prereleased: a pre-release is created
> * released: a release or draft of a …
=> fix: build docker on draft release

libs/mocks/src/pools.rs, libs/test-utils/src/mocks/accountant.rs, libs/traits/src/benchmarking.rs, pallets/foreign-investments/src/impls/benchmark_utils.rs, pallets/investments/src/benchmarking.rs, pallets/loans/src/benchmarking.rs, pallets/pool-system/src/impls.rs
The previous `PoolBenchmarkHelper` utility made use of investment utilities. This forces you to track investment bounds through the code, which is ok for parts that will end to use investments, but for cases where you only want to create a pool, it is boilerplate and annoying to use, carrying information out of the problem scope. This PR splits the current trait into 2 depending on the usage you require.
- Renamed `PoolBenchmarkHelper` to `FundedPoolBenchmarkHelper`, for creating funded pools.
- New `PoolBenchmarkHelper` for only creating just pools.
Required for OracleV2. https://github.com/centrifuge/centrifuge-chain/pull/1629
=> Split concern for pool benchmark helper

.github/workflows/build-docker.yml
This PR:
- Adds an on-demand trigger in case a manual docker tag is needed
- Adjusts when a release triggers a docker build and push
- Auto-comments on the release notes adding the docker tags
=> Fix Docker workflow triggers

Cargo.lock, libs/types/src/tokens.rs, pallets/liquidity-pools/src/lib.rs, runtime/centrifuge/Cargo.toml, runtime/centrifuge/src/lib.rs, runtime/centrifuge/src/migrations.rs, runtime/common/src/xcm.rs, runtime/integration-tests/src/generic/cases/liquidity_pools.rs
Currently, when tokens are transfered to another domain we are storing them in the domain specific account. That is correct for tranche tokens, as Centrifuge Chain is the reserve for these kind of tokens. But all other tokens that are LP transferable are tokens where the domain is the reserve, hence we need to burn them instead. 
This PR fixes the code to burn instead and furthermore provides a migration for Centrifuge Chain to burn existing tokens. 
NOTE: We must burn all LP tokens from this account, as we are now also deployed on `Celo`, `Arbitrum` and `Base` we must be cautious whether we need to extend the burn-migration to `USDC` from these domains.
* use `burn_from` instead of `transfer`
* migration for burning from `Domain` account
=> Fix: LP accounting

pallets/oracle-data-collection/src/benchmarking.rs, pallets/oracle-data-collection/src/lib.rs, pallets/oracle-data-collection/src/tests.rs, runtime/common/src/oracle.rs, runtime/integration-tests/src/generic/cases/loans.rs, runtime/integration-tests/src/generic/utils/mod.rs
We should avoid configuring the feeders with a vector to prevent the caller from adding duplicated feeders. Instead of checking duplications in runtime, we can ensure this behavior in the type system using a set.
* Depends on https://github.com/centrifuge/centrifuge-chain/pull/1658
=> Oracles: Protect from configuring with duplicated feeders

libs/mocks/src/data.rs, libs/traits/src/data.rs, pallets/loans/src/benchmarking.rs, pallets/loans/src/lib.rs, pallets/loans/src/tests/portfolio_valuation.rs, pallets/oracle-data-collection/src/benchmarking.rs, pallets/oracle-data-collection/src/lib.rs, pallets/oracle-data-collection/src/mock.rs, pallets/oracle-data-collection/src/tests.rs, pallets/oracle-data-collection/src/weights.rs, runtime/altair/src/lib.rs, runtime/altair/src/weights/pallet_oracle_data_collection.rs, runtime/centrifuge/src/lib.rs, runtime/centrifuge/src/weights/pallet_oracle_data_collection.rs, runtime/development/src/lib.rs, runtime/development/src/weights/pallet_oracle_data_collection.rs
We want, as a requirement, to have oracle values validated with a "max age" threshold. Older oracles values must be considered outdated and it's an error to use them.
This error is generated when:
- Getting a collection where one oracle is outdated.
- Getting just an oracle value outdated.
- Updating a collection when an oracle value is outdated.
The threshold is optionally set by the collection by the admin
=> Oracles: Time validation by a max age threshold

pallets/liquidity-pools/src/lib.rs, runtime/integration-tests/src/generic/cases/liquidity_pools.rs
Fixes #1677 
Added a permission check for the pool admin role.
=> liquidity-pools: Ensure only pool admins can allow investment currencies

runtime/common/src/remarks.rs
Loan IDs are not unique, therefore, we need to add the `PoolId` to the `Loan` variant of the `Remark` enum.
=> remarks: Add pool ID to loan variant

pallets/oracle-collection/src/benchmarking.rs, pallets/oracle-collection/src/lib.rs, pallets/oracle-collection/src/tests.rs, pallets/oracle-collection/src/weights.rs, runtime/altair/src/weights/pallet_oracle_collection.rs, runtime/centrifuge/src/weights/pallet_oracle_collection.rs, runtime/common/src/changes.rs, runtime/development/src/weights/pallet_oracle_collection.rs, runtime/integration-tests/src/generic/cases/loans.rs, runtime/integration-tests/src/generic/utils/mod.rs
Move the feeder concept by collection instead of by key.
=> Oracles: Move feeders to collection level

.github/workflows/deploy-docs.yml
Since dependabot upgraded the deploy-pages action, the docs deployment to GH pages is broken. This should fix the issue
=> Fix Rust docs broken in main branch

Cargo.lock, pallets/pool-system/src/lib.rs, pallets/pool-system/src/solution.rs, pallets/pool-system/src/tests/mod.rs, runtime/altair/src/migrations.rs, runtime/centrifuge/src/migrations.rs, runtime/common/src/migrations/epoch_execution.rs, runtime/common/src/migrations/mod.rs, runtime/development/Cargo.toml, runtime/development/src/lib.rs, runtime/development/src/migrations.rs
Adaption of the existing feature branch to do a correct epoch execution with the new fees.
=> fix: correct epoch execution with fees

pallets/pool-registry/src/mock.rs
`pallet-pool-registry` compiled without the `runtime-benchmarks` feature does not compile in `main`.
=> Fix: pool-registry test compilation

pallets/foreign-investments/src/impls.rs, pallets/foreign-investments/src/tests.rs
* Adds the pending foreign-to-pool swapping amount to the foreign investment amount `ForeignInvestment::investment`
* Required for cancelling a foreign investment if there is any swapping amount into pool currency
=> fix: foreign investment amount

Cargo.lock, libs/mocks/src/liquidity_pools.rs, libs/mocks/src/liquidity_pools_gateway_routers.rs, libs/primitives/src/lib.rs, libs/traits/src/liquidity_pools.rs, pallets/liquidity-pools-gateway/Cargo.toml, pallets/liquidity-pools-gateway/routers/src/lib.rs, pallets/liquidity-pools-gateway/routers/src/mock.rs, pallets/liquidity-pools-gateway/routers/src/routers/axelar_evm.rs, pallets/liquidity-pools-gateway/routers/src/routers/axelar_xcm.rs, pallets/liquidity-pools-gateway/routers/src/routers/ethereum_xcm.rs, pallets/liquidity-pools-gateway/routers/src/tests.rs, pallets/liquidity-pools-gateway/src/lib.rs, pallets/liquidity-pools-gateway/src/mock.rs, pallets/liquidity-pools-gateway/src/tests.rs, pallets/liquidity-pools-gateway/src/weights.rs, pallets/liquidity-pools/src/message.rs, runtime/altair/src/liquidity_pools.rs, runtime/centrifuge/src/liquidity_pools.rs, runtime/common/src/xcm.rs, runtime/development/src/liquidity_pools.rs, runtime/integration-tests/src/generic/cases/liquidity_pools.rs
Fixes #1694 
- Added storage for outbound messages.
- Added `on-idle` hook logic for processing outbound messages.
- Added `DispatchResultWithPostInfo` to routers for retrieving weight.
- Added storage for failed outbound messages.
- Added extrinsics for manually executing messages.
=> lp-gateway: Add queue for outbound messages

Cargo.lock, libs/mocks/Cargo.toml, libs/mocks/src/asset_registry.rs, libs/mocks/src/lib.rs
The current `cfg_test_utils::impl_mock_registry!` macro works pretty well for most of the cases, establishing the base functionality for an asset registry. But added a mock builder version for cases where we wanted to test some border cases related to the asset registry.
This PR is not mandatory at all and can be left unmerged here until the mock is required by any pallet.
=> Add asset_registry mock

pallets/pool-fees/src/lib.rs, pallets/pool-fees/src/tests.rs
* Changes behavior of pool fees event `Paid` to only be dispatched for non-zero amounts
* Throws `NothingCharged` / `NothingUncharged` error for attempts to (un)charge zero amounts
=> pool fees: explicit handling of zero amounts

libs/types/src/pools.rs, pallets/pool-fees/src/lib.rs, pallets/pool-fees/src/mock.rs, pallets/pool-fees/src/tests.rs, pallets/pool-system/src/lib.rs, runtime/altair/src/lib.rs, runtime/centrifuge/src/lib.rs, runtime/common/src/apis/mod.rs, runtime/common/src/apis/pool_fees.rs, runtime/development/src/lib.rs
* Adds `Accrued` event for fixed fees when they are updated (either manually during NAV update or during epoch 
closing)
```rust
Accrued {
pool_id: T::PoolId,
fee_id: T::FeeId,
pending: T::Balance,
disbursement: T::Balance,
},
```
* Adds PoolFees Runtime API `list_fees` which simulates a PoolFees update and returns the list of pool fees divided by the bucket
```rust
fn list_fees(pool_id: PoolId) -> Option<PoolFeesList>
type PoolFeesList<...> = Vec<PoolFeesOfBucket<...>>;
pub struct PoolFeesOfBucket<FeeId, AccountId, Balance, Rate> {
/// The corresponding pool fee bucket
pub bucket: PoolFeeBucket,
/// The list of active fees for the bucket
pub fees: Vec<PoolFee<AccountId, FeeId, PoolFeeAmounts<Balance, Rate>>>,
}
```
* Adds Pool Fees update to execution of previous epoch
Apps needs to add …
=> feat: add PoolFees RtApi & AccruedFees event

.github/workflows/build-wasm.yml, Cargo.lock, libs/types/src/tokens.rs, runtime/centrifuge/src/lib.rs, runtime/centrifuge/src/migrations.rs, runtime/common/src/migrations/mod.rs, runtime/development/Cargo.toml, runtime/development/src/lib.rs, runtime/development/src/migrations.rs
Some minor changes and updates pre 1030 runtime upgrade
Fixes #(issue)
* Register new canonical Circle `USDC` on Celo
* Rename existing wormhole `USDC`
* NOTE: This version is intentionally NOT a variant of `LocalUSDC`
* Bumb version of dev runtime
* Allow Council, root and LpAdmin to set `MarketFeeder` in the order book for now
=> misc: Clean-up and minors pre 1025

libs/traits/src/swaps.rs, pallets/foreign-investments/src/entities.rs, pallets/foreign-investments/src/impls.rs, pallets/foreign-investments/src/tests.rs, pallets/swaps/src/lib.rs, pallets/swaps/src/tests.rs
The issue is described in this [thread](https://kflabs.slack.com/archives/C04GJQAM9P0/p1707298087515729)
> When we decrease, and there is an increasing pending swap,  we use the `convert_by_market()` to know upfront the amount we need to cancel to the inverse swap and distinguish from the amount we need to decrease the investment.
Nevertheless, later, inside the swap, `convert_by_market()` is called again in the inverse direction to perform the cancellation of the swap. This works fine. However, with asymmetric ratios (A -> B, ratio: 0.9; B -> A, ratio 0.95), it can lead to obtaining a different swap than expected. In the worst case, it would lead to a NoFund error if the amounts are very fit.
Now `pallet-swaps` offer a new method `cancel_swap()` which allows to cancel partially a pending …
=> Fix: FI swap correclty with asymmetric ratios

runtime/altair/src/migrations.rs, runtime/centrifuge/src/migrations.rs, runtime/common/src/migrations/increase_storage_version.rs, runtime/common/src/migrations/mod.rs
Fixes storage version mismatch of external dependencies as well as the decoding issue for the `burn_unburned` migration
NOTE: The burned amount might be a bit outdated as my snapshot is a few days old. 
```
[2024-02-28T14:30:19Z INFO  try-runtime::cli] Original runtime [Name: RuntimeString::Owned("centrifuge")] [Version: 1024] [Code hash: 0xe9ec...5a97]
[2024-02-28T14:30:19Z INFO  try-runtime::cli] New runtime      [Name: RuntimeString::Owned("centrifuge")] [Version: 1025] [Code hash: 0x28cb...c817]
[2024-02-28T14:30:19Z INFO  try_runtime_core::commands::on_runtime_upgrade] 🔬 Running TryRuntime_on_runtime_upgrade with checks: PreAndPost
[2024-02-28T14:30:20Z INFO  runtime_common::migrations::epoch_execution] EpochExecutionMigration:  EpochExecution count pre migration is 0 …
```
=> Fix: storage version mismatch + burn-unburned decoding issue

libs/mocks/src/data.rs, libs/traits/src/data.rs, pallets/loans/src/entities/input.rs, pallets/loans/src/entities/loans.rs, pallets/loans/src/entities/pricing/external.rs, pallets/loans/src/lib.rs, runtime/altair/src/lib.rs, runtime/centrifuge/src/lib.rs, runtime/common/src/apis/loans.rs, runtime/development/src/lib.rs, runtime/integration-tests/src/generic/cases/loans.rs, runtime/integration-tests/src/generic/config.rs, runtime/integration-tests/src/generic/envs/runtime_env.rs, runtime/integration-tests/src/generic/utils/mod.rs
Add a Runtime API to emulate a portfolio update with custom prices.
=> Loans: Runtime API for updating the portfolio with fake prices

pallets/ethereum-transaction/Cargo.toml, pallets/ethereum-transaction/src/lib.rs, pallets/ethereum-transaction/src/tests.rs, pallets/liquidity-pools-gateway/routers/src/tests.rs, runtime/integration-tests/src/evm/ethereum_transaction.rs, runtime/integration-tests/src/generic/cases/liquidity_pools.rs
Currently, the EVM does never error out if the execution of the EVM failed for some reason. In most case it will be an active `Revert` faced from some checks on the EVM side. 
But Substrate does not see that. It will only see an okay, resulting in wrong assumptions. 
NOTE: 
This change does mean that the EVM side DOES change but the Substrate side is still transactional. In most cases the EVM side will only contain fee-payment and new `Pending` appends.
* Check last `Pending` to fetch status code of transaction
=> Feat: Enhance Error Resolution EVM

Cargo.lock, node/Cargo.toml, runtime/centrifuge/Cargo.toml, runtime/centrifuge/src/lib.rs, runtime/centrifuge/src/migrations.rs
Bumps Centrifuge Runtime and Client version by one to signal the addition of #1764 and #1765 to planned runtime upgrade of Centrifuge Chain. As a result, the next Centrifuge runtime version will be 1026 instead of 1025.
=> Centrifuge 1026

README.md, pallets/anchors/src/lib.rs, pallets/block-rewards/src/lib.rs, pallets/bridge/src/lib.rs, pallets/collator-allowlist/src/lib.rs, pallets/crowdloan-claim/src/lib.rs, pallets/crowdloan-reward/src/lib.rs, pallets/ethereum-transaction/src/lib.rs, pallets/foreign-investments/src/lib.rs, pallets/investments/Cargo.toml, pallets/investments/src/lib.rs, pallets/liquidity-pools-gateway/axelar-gateway-precompile/src/lib.rs, pallets/liquidity-pools-gateway/routers/src/lib.rs, pallets/liquidity-pools-gateway/src/lib.rs, pallets/oracle-collection/src/lib.rs, pallets/oracle-feed/src/lib.rs, pallets/order-book/src/lib.rs, pallets/pool-fees/src/lib.rs, pallets/pool-registry/src/lib.rs, pallets/restricted-xtokens/src/lib.rs, pallets/swaps/src/lib.rs, pallets/token-mux/src/lib.rs, pallets/transfer-allowlist/src/lib.rs
Updates to pallet documentation.
=> docs: Update pallet docs

docs/DEVELOPING.md
Updates the developer docs by removing some deprecated bits. All lines were tested locally. Used as base for outstanding _How to contribute_ docs in docs repository.
=> docs: update developing

runtime/altair/src/lib.rs, runtime/centrifuge/src/lib.rs, runtime/development/src/lib.rs
Adds `TokenMux` call permissions to `ProxyType::Borrow`
=> fix: permit token mux calls for `ProxyType::Borrow`

runtime/altair/src/migrations.rs, runtime/centrifuge/src/migrations.rs, runtime/common/src/migrations/increase_storage_version.rs
I'm not sure why the new Oracle pallets added have their on-chain version of 0 when it should be 1. It is not an issue now, but it can be if we update them tomorrow, and makes the new Ci job for migrations fail. This PR set them with the correct version.
My hypothesis of why this has happened is that we reused the previous indexes from the previous oracle pallets (`orml-oracle`, and `pallet-data-collection`), and because of this, it has not update the version (even when the pallet names have changed).
The same happens for `Orderbook` and `ForeignInvestments` for `altair`. Altair didn't require reseting the storage but we did not update the version numbers there.
=> Set correct onchain versions

node/src/chain_spec.rs, runtime/altair/src/lib.rs, runtime/centrifuge/src/lib.rs, runtime/common/src/account_conversion.rs, runtime/common/src/gateway.rs, runtime/development/src/lib.rs, runtime/integration-tests/src/generic/cases/liquidity_pools.rs, runtime/integration-tests/src/utils/evm.rs
From this discussion: https://github.com/centrifuge/centrifuge-chain/pull/1756#discussion_r1559105772
A refactor of `AccountConverter`:
- All methods belong to `AccountConverter` type.
- If the method requires the type to have a runtime type, then it uses the wrapper `RuntimeAccountConverter` type. This should only be used by trait demands in pallet configurations. For simple calls, use always `AccountConverter`
Are we in a middle point with this PR @mustermeiszer?
=> Polkadot v1.1.0: Account converter changes

node/src/chain_spec.rs
As part of my #1756 client checks, I noticed that our ephemeral chain specs did not lead to a deterministic chain spec which blocks all our scripts to register such parachain. The root of this was introduced by myself in #1740 by adding a unix timestamp for the block rewards. Since this timestamp is completely irrelevant for ephemeral chains, I changed it to the default value. This will mint a larger amount of treasury inflation in the first session and then go back to normal.
=> fix: chain spec not deterministic

docs/DEVELOPING.md, node/src/chain_spec.rs, node/src/command.rs, scripts/check_benchmarks.sh, scripts/export_parachain_files.sh, scripts/runtime_benchmarks.sh
Context: https://github.com/centrifuge/centrifuge-chain/pull/1756/files#r1562566212
* Deprecates `parachain-id` CLI argument which was a custom addition for a few CLI arguments inherited from Substrate
* Sets para id `2000` for ephemeral chain specs `development`, `centrifuge-local`, `altair-local`
* Removes defaulting to `10001` para id if not set in CLI
* Removes deprecated chain specs `charcoal`, `algol`, `centrifuge-dev` (basically `centrifuge-local with 2 more funded accounts) and `altair-dev` (basically `altair-local` with 2 more funded accounts)
Fixes #(issue)
* Local parachain deploymentg
=> fix: polkadot v1.1.0 client

pallets/pool-fees/src/lib.rs, runtime/common/src/lib.rs
The NAV runtime-apis need to be super stable for the UI. This defaults them to use the latest computed price if the latest calculation fails. 
* use previously computed valuation amount for `nav_loans`
* use previously computed valuation amount for `nav_fees`
=> Fix: mostly non failable runtime-api

pallets/pool-system/src/lib.rs, pallets/pool-system/src/pool_types.rs, pallets/pool-system/src/tests/mod.rs
[Slack thread](https://kflabs.slack.com/archives/C04GJQAM9P0/p1712041396660229)
We can hold this until #1756 is merged
* Fixes incorrect tranche token metadata reported by pool system `essence` which is used for `Updated` event
* Adds missing unit test which asserts condition
=> fix: essence tranche token metadata

pallets/liquidity-pools-gateway/routers/Cargo.toml, pallets/liquidity-pools-gateway/routers/src/lib.rs, pallets/liquidity-pools/src/routers.rs, pallets/pool-system/src/pool_types.rs
We had some `MaxEncodingLen` traits implemented manually for some types. Since `polkadot-v1.1.0`, it seems we can get rid of our custom implementation and let Rust do it for us.
**NOTE**: Blocked until `v1.1.0`
=> Remove custom implementation for `MaxEncodingLen`

pallets/block-rewards/src/lib.rs, pallets/block-rewards/src/mock.rs, pallets/block-rewards/src/tests.rs, runtime/altair/src/lib.rs, runtime/centrifuge/src/lib.rs, runtime/common/src/lib.rs, runtime/development/src/lib.rs
I guess this comes from the previous upgrade when balance/and currencies force `ExistentialDeposit` usage.
Issue 1: We're using an `ED` denominated in `CFG` for the `StakingCurrency`. This is not critical if both currencies use the same denomination, but we should use the correct `ED` for Staking. 
Issue 2: Because `Staking` currencies were not in the asset registry. From `orml_tokens` perspective, the `ED` is `0` while from `block-rewards` perspective it's `1 * MICRO_CFG`. I guess this is not a problem for us right now, but it should be fixed to avoid future problems.
=> BlockRewards: Fix how it handle ED for Staking currency.

pallets/foreign-investments/src/tests.rs, pallets/order-book/src/tests.rs, pallets/swaps/src/lib.rs, pallets/swaps/src/tests.rs
There are two casuistics where an order can contain a zero amount. Such an order can not be closed, and theoretically, it should not exist.
Q: Should we allow to close zero orders even though they should not be possible now?
=> Fix: zero amount order bug

libs/types/src/tokens.rs, pallets/foreign-investments/src/tests.rs, pallets/order-book/src/tests.rs, pallets/swaps/src/lib.rs, pallets/swaps/src/tests.rs, pallets/token-mux/src/mock.rs, pallets/token-mux/src/tests.rs
Fixes issue which blocks FRAX <> USDC order fulfilments on Demo.
The current implementation of `is_local_representation` is too strict such that it throws an error if the checked `CurrencyId` has not configured a local representation. Instead, it should return `Ok(false)`. This function has not been tested directly. 
To the best of my knowledge, this does not affect production for now as it only affects checking currencies which don't have a configured local asset, e.g. FRAX.
=> fix: looser `is_local_representation`

pallets/loans/src/lib.rs, pallets/loans/src/tests/mod.rs, pallets/loans/src/tests/repay_loan.rs, pallets/loans/src/tests/transfer_debt.rs
`TransferEvent` was set with the initial `repaid_amount`. That amount changes once it is processed and could not be the amount that it's really applied.
=> Fix: transfer debt event with updated repaid amount

libs/types/src/oracles.rs
The DYF will have shares of other funds as its assets. Those fund holdings are valued by an oracle, but have not a valid registered ISIN we could use. Hence, this fallback key will allow to specifically value a given object in the `pallet-loans`.
* Adds a new variant in `enum OracleKey`
* Fixes all variants by using `#[codec(index = ...)`
=> Feat: Add new oracle key

pallets/loans/src/entities/loans.rs, pallets/loans/src/entities/pricing/external.rs, pallets/loans/src/tests/mod.rs, pallets/loans/src/tests/repay_loan.rs
[slack thread](https://kflabs.slack.com/archives/C04GJQAM9P0/p1715955299145219?thread_ts=1715935675.464829&cid=C04GJQAM9P0)
We need to avoid computing points in the line of linear accrual if the time overpass the maturity time, instead, we want to clamp the value to `notional` (which is the same when the time is just maturity)
=> Fix: linear accrual not overpassing maturity

runtime/integration-tests/procedural/src/lib.rs, runtime/integration-tests/src/generic/cases/liquidity_pools.rs, runtime/integration-tests/src/generic/envs/fudge_env.rs, runtime/integration-tests/src/generic/envs/runtime_env.rs, runtime/integration-tests/src/generic/mod.rs
I forgot to update the `liquidity_pools.rs` file in https://github.com/centrifuge/centrifuge-chain/pull/1821
=> IT: Add test_runtimes macro to liquidity_pools tests

runtime/altair/src/migrations.rs, runtime/centrifuge/src/migrations.rs, runtime/common/src/migrations/hold_reason.rs, runtime/common/src/migrations/mod.rs, runtime/development/src/migrations.rs
* Provides necessary migrations for Polkadot v1.7.2 including migration of 
``` diff
- type RuntimeHoldReason = ()
+ type RuntimeHoldReason = RuntimeHoldReason
```
* Fixes existing migrations for Dev and Demo
* Tested against all runtimes Dev, Demo, Altair and Centrifuge
One decoding error is left in the logs but this does not require a migration and will be fixed just by upgrading to the newer Polkadot SDK version. It was an oversight from the frame team and should have bumped the `ParachainSystem` storage version as well as required a migration. Check [this conversation](https://github.com/paritytech/polkadot-sdk/issues/4603) for more info.
```
[2024-05-31T08:00:55Z ERROR runtime::executive] `try_decode_entire_state` failed with 1 errors
[2024-05-31T08:00:55Z ERROR runtime::executive] - …
```
=> feat: Polkadot v1.7.2 migrations

pallets/loans/src/benchmarking.rs, pallets/loans/src/tests/mock.rs
Some benchmark testing with loans is a bit annoying because the log is filled with a lot of `pallet_timestamps` errors, adding noise to the debugging process. This PR removes that pallet and use the `MockTimer` instead
=> Loans: use mocked timer

runtime/altair/src/lib.rs, runtime/centrifuge/src/lib.rs, runtime/development/src/lib.rs
We want the `ProxyType::Borrow` to also behaves as the `ProxyType::PodOperation`. Thread: https://kflabs.slack.com/archives/C04GJQAM9P0/p1717154483749839
=> Borrow proxy with PodOperation behavior

pallets/pool-fees/src/lib.rs, pallets/pool-fees/src/mock.rs, pallets/pool-fees/src/tests.rs
Fixes https://github.com/centrifuge/centrifuge-chain/issues/1847
* Feat: Allow `root` origin for proposing fees
* Fix: Allow `root` origin for removing fees if fee editor is configured as `Root`
=> fix: allow root to propose and remove fees

pallets/loans/src/lib.rs, pallets/loans/src/tests/borrow_loan.rs, pallets/loans/src/tests/repay_loan.rs
Allows issuers to decrease the debt of any loan without actually repaying to the pool. Mostly useful for ensuring offchain cash is reflected accurately. This is basically an expense in most cases, should be covered by fees, but is a good increase of flexibility.
NOTE:
* The deployed capital ratio of the tranches will decrease during the next epoch close but until then the tranches expect to generate the same revenue as of before - i.e. with a higher deployed capital ratio
* adds  extrinsic `fn decrease_debt(..)` - same as `fn repay(..)` but without moving tokens to the pool
=> Feat: decrease debt

pallets/pool-system/src/lib.rs, pallets/pool-system/src/mock.rs, pallets/pool-system/src/tests/mod.rs, pallets/pool-system/src/tests/ratios.rs, pallets/pool-system/src/tranches.rs
The current ratio calculation has the following bug. The logic assumes that `Sum(tranche.supply) = total_assets`, but as the residual tranche does only receive its variable interest after the ratio calculation, this is not true. 
In order to fix this, the following change does give the automatically all the remaining ratio to the residual tranche.
* Adds a test to ensure ratios are actually adapting accordingly
* Changes ratio calculation during `fn do_execute_epoch`
=> Fix: `pallet-pool-system` - Ratio Calculation

.github/workflows/sanity-checks.yml
* Fixes over aggressive reversion of changes in https://github.com/centrifuge/centrifuge-chain/pull/1822 in commit https://github.com/centrifuge/centrifuge-chain/pull/1822/commits/5d4acff282cd93edf60de02913ad0603ee9c1cda
* Enables submodule pulling in CI such that LP integration test build should work
=> ci: re-enable submodule pulling

Cargo.lock, libs/types/src/locations.rs, pallets/restricted-xtokens/src/lib.rs, pallets/transfer-allowlist/src/benchmarking.rs, pallets/transfer-allowlist/src/lib.rs, pallets/transfer-allowlist/src/mock.rs, pallets/transfer-allowlist/src/tests.rs, runtime/centrifuge/src/migrations.rs, runtime/common/Cargo.toml, runtime/common/src/migrations/mod.rs, runtime/common/src/migrations/restricted_location.rs, runtime/common/src/transfer_filter.rs, runtime/development/Cargo.toml, runtime/development/src/migrations.rs, runtime/integration-tests/src/generic/cases/liquidity_pools.rs, scripts/runtime_benchmarks.sh
Modify how RestrictedTransferLocation stores XCM information and do the consequent migration. Based on this https://github.com/centrifuge/centrifuge-chain/pull/1833#discussion_r1604512221
=> Polkadot-1.7.2: restricted transfer location changes

pallets/loans/src/entities/loans.rs, pallets/loans/src/entities/pricing/external.rs, pallets/loans/src/lib.rs, pallets/loans/src/tests/borrow_loan.rs, pallets/loans/src/tests/mod.rs, pallets/loans/src/tests/util.rs, pallets/loans/src/types/cashflow.rs
External pricing loan with correct cashflow computation.
For computing interest of:
- internal loans: we use `debt - principal`
- external loans: we use `debt - notional`
From the cashflow perspective, we can emulate the `debt` at maturity given the `interest` and `principal` parameters given to the `expected_cashflows()`. Nevertheless, in the case of external loans, the principal used for computing the debt is different from the value substracted to the debt to obtain the interest. We need to pass a new parameter to `expected_cashflows()`. Called `principal_base`, which is the unaltered principal. It maps to `principal` for internal pricing and `notional` for external pricing.
=> Loans: multi cashflows fix external loan

runtime/integration-tests/src/generic/cases/routers.rs, runtime/integration-tests/src/generic/env.rs
The current behavior for `env.pass(Blocks::UntilEvent{event, limit})` evolve the chain a maximum blocks of `limit` looking for the event. Nevertheless if the event is not found nothing happens. 
That means that later, we need to ensure that the event is found. We can avoid that if we panic if the event is not found during `pass()` method.
=> IT: Panic if event is not found in the expected blocks

libs/mocks/src/investment.rs, libs/traits/src/investments.rs, pallets/investments/src/lib.rs, runtime/integration-tests/src/cases/liquidity_pools.rs
It seems these lines are no longer needed from the past FI refactorization.
=> Clean: remove some unused code from investment trait

pallets/liquidity-pools/src/tests.rs, runtime/integration-tests/src/cases/liquidity_pools.rs, runtime/integration-tests/src/cases/lp/pool_management.rs
Add UTs to `update_member()` and remove unitary testing from integration tests related to it.
@wischli I've done over `main` because it should not conflict with the current lpv2 work. Maybe just a minor import.
=> LP: Add Unitary Tests for update_member()

runtime/integration-tests/procedural/src/lib.rs, runtime/integration-tests/procedural/tests/lib.rs, runtime/integration-tests/src/lib.rs
Gives support to ignore tests in integration tests with the `#[test_runtimes()]` macro.
Using ignore instead of commenting the test helps to not forget and leave the test commented when it could be fixed.
Now: 
```rust
#[test_runtimes([development, altair, centrifuge], ignore)]
// or
#[test_runtimes([development, altair, centrifuge], ignore = "reason")]
```
NOTE: useful to work smoothly in the lpv2 branch when solidity/centrifuge-chain don't match correctly.
=> IT: Support `#ignore = reason` for `test_runtimes` macro

runtime/integration-tests/src/cases/lp/investments.rs, runtime/integration-tests/src/cases/lp/transfers.rs
We want to mark them as `ignore` not to forget them later when they work again
=> Lpv2: ignore failing tests

.github/workflows/sanity-checks.yml
Goal: Reduce CI overload
* Disables CI checks on draft PRs
* Removes `altair` runtime from benchmark checks
=> ci: disable checks for drafts

runtime/integration-tests/src/cases/liquidity_pools.rs
Fix failing FI-related tests found in `feat/lp-v2`
=> LPv2: Fix foreign-investments ITs

pallets/liquidity-pools/src/mock.rs, pallets/liquidity-pools/src/tests.rs, pallets/liquidity-pools/src/tests/inbound.rs
Unitary tests for inbound messages
NOTE. The decrease and collection-related inbound messages are not tested because they are deprecated in LPV2
=> LP: Unitary testing for inbound messages

Cargo.lock, libs/mocks/src/outbound_queue.rs, libs/traits/src/liquidity_pools.rs, libs/types/src/consts.rs, pallets/liquidity-pools-gateway/Cargo.toml, pallets/liquidity-pools-gateway/src/lib.rs, pallets/liquidity-pools-gateway/src/mock.rs, pallets/liquidity-pools-gateway/src/tests.rs, pallets/liquidity-pools/src/lib.rs, pallets/liquidity-pools/src/mock.rs, pallets/liquidity-pools/src/tests.rs, runtime/altair/src/lib.rs, runtime/centrifuge/src/lib.rs, runtime/development/src/lib.rs, runtime/integration-tests/src/cases/lp/mod.rs, runtime/integration-tests/src/cases/lp/pool_management.rs, runtime/integration-tests/src/cases/lp/setup_lp.rs
* Replaces hardcoded `AddTrancheHookAddress` with `DomainHookAddress` storage because it is different for every domain
* @mustermeiszer recommended adding the storage to the gateway instead of the LP pallet
* Extends gateway tests by also checking LP Admin account origin
=> feat: add domain hook storage

runtime/altair/src/lib.rs, runtime/centrifuge/src/lib.rs, runtime/development/src/lib.rs
Needed for apps
* Adds `pallet_remarks::Call::remark` to the allowed calls for `ProxyType::Borrow`
=> fix: add remark call to borrow proxy

runtime/development/src/lib.rs
Adds access to the Anchors V2 calls to the `PodOperation` proxy type.
=> development: Add Anchors V2 to PodOperation proxy

runtime/integration-tests/src/cases/liquidity_pools.rs, runtime/integration-tests/src/cases/lp/investments.rs, runtime/integration-tests/src/cases/lp/pool_management.rs, runtime/integration-tests/src/cases/lp/transfers.rs
Reverts previous convenience change of running ITs solely for Development runtime. Since LPs are not expected to be used on Altair for now, we save time by running them solely on Centrifuge and Development runtimes
=> refactor: enable ITs for centrifuge + dev runtimes

runtime/altair/src/lib.rs, runtime/centrifuge/src/lib.rs, runtime/development/src/lib.rs
=> Add increase & decrease debt to borrow proxy

libs/mocks/src/liquidity_pools_gateway_queue.rs, pallets/liquidity-pools-gateway/src/lib.rs, pallets/liquidity-pools-gateway/src/tests.rs
=> LPv2: UTs for Batches

pallets/liquidity-pools-gateway/src/lib.rs, pallets/liquidity-pools-gateway/src/message_processing.rs, pallets/liquidity-pools-gateway/src/mock.rs, pallets/liquidity-pools-gateway/src/tests.rs
Addressing some comments from - https://github.com/centrifuge/centrifuge-chain/pull/1961.
=> lp-gateway: Drop session ID invalidation

pallets/liquidity-pools-gateway/src/lib.rs, pallets/liquidity-pools-gateway/src/message_processing.rs
Small PR to move the weight checks to `MessageProcessor`.  
Like the fact that now only the `MessageProcessor` trait implementation knows about weights
=> LPv2: Isolate gateway weights

libs/traits/src/liquidity_pools.rs, pallets/liquidity-pools-gateway/src/lib.rs, pallets/liquidity-pools-gateway/src/message.rs, pallets/liquidity-pools-gateway/src/message_processing.rs, pallets/liquidity-pools-gateway/src/mock.rs, pallets/liquidity-pools-gateway/src/tests.rs, pallets/liquidity-pools-gateway/src/weights.rs, pallets/liquidity-pools/src/message.rs, runtime/integration-tests/src/cases/liquidity_pools.rs, runtime/integration-tests/src/cases/liquidity_pools_gateway_queue.rs, runtime/integration-tests/src/cases/lp/utils.rs, runtime/integration-tests/src/cases/routers.rs
Added:
- new extrinsics for initiating and disputing message recovery.
- new gateway events when processing inbound and outbound messages.
Changed:
- renamed `LPEncoding` to `LPMessage`.
- added new methods from getting dispute messages.
- changed message hash method.
=> lp-gateway: Add extrinsics for initiating and disputing message recovery

libs/traits/src/liquidity_pools.rs, pallets/liquidity-pools-gateway/src/lib.rs, pallets/liquidity-pools-gateway/src/mock.rs, pallets/liquidity-pools-gateway/src/tests.rs, pallets/liquidity-pools/src/message.rs
- extract domain from router ID - [discussion](https://github.com/centrifuge/centrifuge-chain/pull/1970#discussion_r1720717386)
- change message recovery arg type - [discussion](https://github.com/centrifuge/centrifuge-chain/pull/1970#discussion_r1720762179)
=> Message recovery follow ups

libs/traits/src/liquidity_pools.rs, pallets/liquidity-pools-forwarder/src/lib.rs, pallets/liquidity-pools-forwarder/src/mock.rs, pallets/liquidity-pools-gateway/src/lib.rs, pallets/liquidity-pools-gateway/src/message_processing.rs, pallets/liquidity-pools-gateway/src/mock.rs, pallets/liquidity-pools-gateway/src/tests.rs, pallets/liquidity-pools/src/message.rs, runtime/common/src/routing.rs, runtime/integration-tests/src/cases/routers.rs
Split the different behaviors of `LpMessage` in subtraits that can be handled separately. See [this thread](https://github.com/centrifuge/centrifuge-chain/pull/1971#discussion_r1720826602)
NOTE: It is not mandatory to be merged before the audit. Also does not requite to update any doc.
=> Split LpMessage traits in subtraits

runtime/common/src/remarks.rs
Fixes #1960 
Added new enum variant `Extrinsic` to `Remark`.
=> remarks: Add new enum for extrinsics

pallets/liquidity-pools/src/message.rs
This issue fixes the `max_encoded_len()` to avoid infinite computation in `Message` type.
This PR fixes our benchmarking CI job, which passes even encountering the error
=> Fix: avoid infinite recursion with Message::max_encoded_len()

pallets/pool-system/src/impls.rs
See issue
Fixes #1989
* just adds fees to tranche token price calculation
=> fix: add fees in TT price calculation

pallets/liquidity-pools-gateway-queue/src/lib.rs, pallets/liquidity-pools-gateway-queue/src/tests.rs, runtime/integration-tests/src/cases/lp/utils.rs
Addressing the comment regarding LP gateway queue message processing:
https://github.com/centrifuge/centrifuge-chain/pull/1991#discussion_r1766659178
=> lp-gateway-queue: Ensure messages are processed in order

ci/check_runtime_changes.sh, pallets/liquidity-pools/src/lib.rs, pallets/pool-system/src/tranches.rs
This pull request contains changes to improve clarity, correctness and structure.
Description correction:
Corrected `sucessfully` to `successfully`
Corrected `not a a wrapped` to `not a wrapped`
Corrected `than the the left` to `than the left`
Please review the changes and let me know if any additional changes are needed.
=> fix: typos in documentation files
