centrifuge/centrifuge-chain

runtime/src/anchor/mod.rs, runtime/src/anchor/tests.rs, runtime/src/lib.rs
Once this is in, I will add the functional tests.
Closes #84
=> add move_anchor dispatch

runtime/src/anchor/mod.rs, runtime/src/anchor/tests.rs, runtime/src/fees.rs, runtime/src/lib.rs, runtime/src/nfts.rs, runtime/src/proofs.rs
=> add nft module

runtime/src/anchor/mod.rs, runtime/src/fees.rs, runtime/src/lib.rs, runtime/src/nfts.rs, src/chain_spec.rs
https://centrifuge.hackmd.io/@vim/centchain/%2F1UFooa4JQDmaWu8AJLOyzw
=> Weight configuration

runtime/src/nfts.rs, runtime/src/proofs.rs
Update NFT proof validations with static tree structure
=> update nft proof validations to support static proofs

Cargo.lock, runtime/Cargo.lock, runtime/Cargo.toml, runtime/src/lib.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/centrifuge/centrifuge-chain/203)
=> Integrate multi-account pallet

ci/check_runtime_changes.sh
=> fix: fail the entire script when git fails

Cargo.lock, runtime/Cargo.lock, runtime/Cargo.toml, runtime/src/lib.rs
Resolved issue #189 
Request for comment on:
- type Slashed = ()
- identity pallet is added to the runtime, is this a breaking change?
=> Integrate identity pallet

Cargo.lock, runtime/Cargo.lock, runtime/Cargo.toml, runtime/src/bridge.rs, runtime/src/lib.rs, runtime/src/nfts.rs, src/chain_spec.rs
This includes latest changes on bridge pallet:
- Wrapped admin operations into private functions
- Enable admin operations to use council voting
Allow genesis setup on dev/local/fulvous to whitelist bridge data.
=> Update Bridge version + dev fixture data

Cargo.lock, ci/script.sh, runtime/Cargo.lock, runtime/Cargo.toml, runtime/src/lib.rs, src/chain_spec.rs
This code is recovered from [this pr](https://github.com/centrifuge/centrifuge-chain/pull/196/files)
Resolves #230
=> integrate pallet-indices

runtime/src/lib.rs, runtime/src/nfts.rs, src/chain_spec.rs
Tried to make this PR as verbose as possible about the pieces of the bridge that should not be in the next release, so we can get them back in as easy as possible.
=> Comment out bridge logic

Cargo.lock, Cargo.toml, runtime/Cargo.lock, runtime/Cargo.toml, runtime/src/lib.rs, src/chain_spec.rs
This PR adds a migration:
- Remove slash data
- Add 63 rad balance to the CNFProxy account
=> add slash storage clear and account balance update

.github/workflows/build.yml
I need to merge this to test what will happen in master.
=> Fixing branch name check

.github/workflows/tests.yml, ci/script.sh, pallets/bridge-mapping/src/lib.rs, pallets/bridge-mapping/src/mock.rs, pallets/bridge-mapping/src/tests.rs, pallets/bridge-mapping/src/weights.rs
This PR:
- Migrates bridge mapping to new pallet frame V2
- Run tests on action for bridge mapping only
=> Pallet frame v2: bridge mapping

runtime/src/lib.rs, src/chain_spec.rs
This PR adds session pallets to inject session keys for collators during genesis and also makes it easier to migrate to staking later
=> add session pallet to inject collator session keys

.github/workflows/docker.yml
=> add workflow dispatch for docker

Cargo.lock, libs/common-traits/src/lib.rs, pallets/loan/Cargo.toml, pallets/loan/src/lib.rs, pallets/loan/src/loan_type.rs, pallets/loan/src/math.rs, pallets/loan/src/tests.rs, runtime/common/src/fixed_point.rs
Implementation of Nav v1 as per spec: https://centrifuge.hackmd.io/SKpjZILDQlCV0ORshhYAjw?both
=> Borrower: Nav v1

Cargo.lock, libs/common-traits/src/lib.rs, pallets/loan/Cargo.toml, pallets/loan/src/functions.rs, pallets/loan/src/lib.rs, pallets/loan/src/loan_type.rs, pallets/loan/src/math.rs, pallets/loan/src/mock.rs, pallets/loan/src/tests.rs, pallets/loan/src/types.rs, pallets/pool/Cargo.toml, pallets/pool/src/lib.rs, runtime/common/src/impls.rs, runtime/common/src/lib.rs
Spec: https://centrifuge.hackmd.io/SKpjZILDQlCV0ORshhYAjw#Write-Off
=> Write off groups

scripts/run_benchmark.sh
Follow up to https://github.com/centrifuge/centrifuge-chain/pull/542/files/2fb0fab81732ad13f4af9081fc0b9abe0b1f1816#diff-ebdd7424557fd25bf9c99f20f316fdc3614c338daefb0e198fe87ddf4d0cf7d2
=> benchmarking: reduce number of steps and repeat

pallets/loans/src/mock.rs, pallets/pools/src/lib.rs, pallets/pools/src/mock.rs, runtime/development/Cargo.toml, runtime/development/src/lib.rs
Use a `BoundedVec` for the metadata of a pool instead of a simple `Vec`
=> Pool Metadata with BoundedVev

pallets/pools/src/lib.rs, pallets/pools/src/tests.rs
This PR fixes https://github.com/centrifuge/centrifuge-chain-internal/issues/2. 
Furthermore, it refactors the extrinsics code a bit.
=> Fix: Out of bounds error with user defined `TrancheId`

pallets/permissions/src/lib.rs
closes https://github.com/centrifuge/centrifuge-chain/issues/605
=> Use contains_key instead of try_get().is_some()

pallets/loans/src/mock.rs, pallets/pools/src/lib.rs, pallets/pools/src/mock.rs, pallets/pools/src/tests.rs, runtime/development/src/lib.rs
Also replaces custom `Overflow` error in pools pallet with standard arithmetic errors.
=> feat: add runtime level pool parameter bounds

pallets/pools/src/lib.rs
This new extrinsic allows another account to cause a collection in a
permissionless way.
It is not benchmarked separately from `collect`
=> Add `collect_for` extrinsic

pallets/pools/src/lib.rs, pallets/pools/src/tests.rs
=> Error handling for impl PoolReserve in pallet-pools

pallets/loans/src/mock.rs, pallets/loans/src/test_utils.rs, pallets/pools/src/lib.rs, pallets/pools/src/mock.rs, pallets/pools/src/tests.rs, runtime/development/src/lib.rs
=> Restrict pools.create() origin

Cargo.lock, README.md, libs/common-traits/src/lib.rs, libs/common-types/src/tokens.rs, libs/proofs/Cargo.toml, pallets/loans/src/test_utils.rs, pallets/loans/src/tests.rs, pallets/permissions/src/lib.rs, pallets/pools/Cargo.toml, pallets/pools/src/benchmarking.rs, pallets/pools/src/lib.rs, pallets/pools/src/mock.rs, pallets/pools/src/solution.rs, pallets/pools/src/tests.rs, pallets/pools/src/tranche.rs, pallets/pools/src/weights.rs, runtime/common/src/impls.rs
The main PR for the pool refactoring. Tracks closing of issues.
Closes #591
Closes #618 
Closes #631
Closes #633
Closes #642
Closes #599
=> Pool Refactoring - Main PR

scripts/init.sh
This helps go-centrifuge testworld to run without the need of having to compile our chain.
=> Support exporting state & wasm from docker image

Cargo.lock, Cargo.toml, libs/common-types/src/lib.rs, libs/common-types/src/tests.rs, libs/common-types/src/tokens.rs, pallets/loans/src/mock.rs, pallets/loans/src/test_utils.rs, pallets/loans/src/tests.rs, pallets/pools/Cargo.toml, pallets/pools/src/lib.rs, pallets/pools/src/mock.rs, pallets/pools/src/tests.rs, pallets/pools/src/tranche.rs, runtime/altair/Cargo.toml, runtime/altair/src/lib.rs, runtime/common/src/lib.rs, runtime/development/src/lib.rs
This PR does implement a way to actually insert, remove, append tranches arbitrarily.
Closes https://github.com/centrifuge/centrifuge-chain/issues/681
=> Adds unique tranche ids

pallets/loans/src/benchmarking.rs, pallets/loans/src/functions.rs, pallets/loans/src/lib.rs, pallets/loans/src/loan_type.rs, pallets/loans/src/math.rs, pallets/loans/src/test_utils.rs, pallets/loans/src/tests.rs, pallets/loans/src/types.rs
Resolves https://github.com/centrifuge/centrifuge-chain/issues/717 
- Make `origination_date` an `Option`
- `rate_per_sec` => `interest_rate_per_sec`
- `latest_nav` => `latest`
- Burn loan NFTs
=> Loan types cleanup

pallets/pools/src/tests.rs
The test added as part of #719 needed a quick fix for the renames
from #727
=> Fix newly-added test for renaming changes

pallets/pools/src/benchmarking.rs, pallets/pools/src/lib.rs, pallets/pools/src/mock.rs, pallets/pools/src/tests.rs, runtime/development/src/lib.rs
- Restructure `PoolDetails`
- Rename `PoolDetails`  impl methods
=> Pools improvements

pallets/loans/src/functions.rs, pallets/loans/src/tests.rs
=> fix: pricing active but non borrowed against loans should be possible

runtime/centrifuge/src/lib.rs
Part of https://github.com/centrifuge/centrifuge-chain/issues/625
=> centrifuge: Update MinimumDeposit to 1000 CFG

pallets/migration/src/lib.rs, pallets/migration/src/mock.rs, pallets/migration/src/tests.rs, runtime/altair/src/lib.rs, runtime/development/src/lib.rs
Part of https://github.com/centrifuge/centrifuge-chain/issues/625
In a follow up PR, I will add this pallet to the `centrifuge-runtime`
=> pallets-migration: Drop filtering logic

pallets/claims/README.md, pallets/claims/src/lib.rs, pallets/claims/src/mock.rs, pallets/claims/src/tests.rs, runtime/centrifuge/src/lib.rs, runtime/development/src/lib.rs
Part of https://github.com/centrifuge/centrifuge-chain/issues/625
=> claims: remove unsigned

Cargo.lock, runtime/centrifuge/Cargo.toml, runtime/centrifuge/src/lib.rs, src/chain_spec.rs
=> PRTU 2 - Decentralize + Enable all Calls

Cargo.lock, runtime/integration-tests/Cargo.toml, runtime/integration-tests/src/lib.rs, runtime/integration-tests/src/pools/env.rs, runtime/integration-tests/src/pools/mod.rs, runtime/integration-tests/src/pools/pool_starts.rs, runtime/integration-tests/src/pools/utils/accounts.rs, runtime/integration-tests/src/pools/utils/env.rs, runtime/integration-tests/src/pools/utils/extrinsics.rs, runtime/integration-tests/src/pools/utils/logs.rs, runtime/integration-tests/src/pools/utils/mod.rs
A lot of utilities we are going to need and testing if the provided env works.
=> Integration Utilities and Testing Env

runtime/development/src/lib.rs
=> Use restricted-tokens-in-pool

libs/common-types/src/lib.rs, pallets/loans/src/benchmarking.rs, pallets/loans/src/lib.rs, pallets/loans/src/mock.rs, pallets/loans/src/tests.rs, runtime/integration-tests/src/pools/utils/pools.rs
To address part of https://github.com/centrifuge/centrifuge-chain/issues/799
=> Rename risk admins to loan admins

Cargo.lock, runtime/development/Cargo.toml, runtime/development/src/lib.rs
- dev: Expose `OrmlAssetRegistry` extrinsics
- dev: Bump Bump spec_version to 1003
=> development: Bump spec_version to 1003

README.md
This PR is what I wanted to find in the test section of the readme as a newcomer, from the perspective of anyone who doesn't know the project. 
It's possible that I may have been confused with some minor concept, so do not take it as truth and be hard in the review 😄 and feel free to tell me if I should revert some changes.
=> Improved the Readme test section

pallets/permissions/src/lib.rs
Related to: https://github.com/centrifuge/centrifuge-chain/issues/871
=> Used struct events in permissions pallet

pallets/claims/src/lib.rs
Related to: https://github.com/centrifuge/centrifuge-chain/issues/871
=> Used struct events in claims pallet

pallets/collator-allowlist/src/lib.rs
Related to: https://github.com/centrifuge/centrifuge-chain/issues/871
=> Used struct events in collator-allowlist pallet

pallets/keystore/src/lib.rs, pallets/keystore/src/tests.rs
Related to: https://github.com/centrifuge/centrifuge-chain/issues/871
=> Used struct events in keystore pallet

pallets/pools/src/impls.rs
Code improvement suggestions left for #881
=> Token price trait - Code improvement suggestions

pallets/loans/src/loan_type.rs, pallets/pools/Cargo.toml
Minor change: Just doesn't like default type for such a complex type and it was not used anywhere.
=> Removes the default `LoanType`

pallets/loans/src/benchmarking.rs, pallets/loans/src/functions.rs, pallets/loans/src/lib.rs, pallets/loans/src/tests.rs
Tasks:
Closes https://github.com/centrifuge/centrifuge-chain/issues/864
=> Pricing ongoing loans

Cargo.lock, flake.nix, runtime/altair/Cargo.toml, runtime/altair/src/lib.rs, runtime/altair/src/xcm.rs, runtime/centrifuge/Cargo.toml, runtime/centrifuge/src/lib.rs, runtime/centrifuge/src/xcm.rs, runtime/development/Cargo.toml, runtime/development/src/lib.rs, runtime/development/src/xcm.rs, runtime/integration-tests/src/xcm/kusama/mod.rs, runtime/integration-tests/src/xcm/kusama/restricted_calls.rs, runtime/integration-tests/src/xcm/polkadot/tests/asset_registry.rs, runtime/integration-tests/src/xcm/polkadot/tests/mod.rs, runtime/integration-tests/src/xcm/polkadot/tests/restricted_calls.rs
Closes #878 
`dev`
`altair`
`centrifuge`
=> Filter tranche transfers

libs/common-types/src/lib.rs, pallets/fees/src/lib.rs, runtime/altair/src/lib.rs, runtime/centrifuge/src/lib.rs, runtime/development/src/lib.rs, src/chain_spec.rs
=> Fee kee variants and events

docs/DEVELOPING.md, docs/runtime-upgrade.md
Added specific doc to test a runtime upgrade locally.
Closes https://github.com/centrifuge/centrifuge-chain/issues/971
=> add runtime upgrade docs

.github/pull_request_template.md, .github/workflows/build-nix.yml, .github/workflows/build.yml, .github/workflows/docker-nix.yml, .github/workflows/docker.yml, .github/workflows/docs.yml, .github/workflows/tests.yml, README.md, flake.nix
Prepare moving away from parachain in benefit of main branch & release branches
Fixes # (issue)
N/A
=> Preparing main & release branch jobs

pallets/permissions/src/lib.rs
When we use the extrinsics for adding and removing permissions, we trigger an event. But when we use the trait logic we DID NOT trigger an event. This inconsistent behaviour is opaque and misleading. 
This PR fixes this. 
Closes #1007 
Simply moved the triggering of the event into the `do_add` and `do_remove` logic.
No additional tests needed, as we do not test for Event signaling in the permissions pallet.
=> Pallet-Permissions: Trigger Events Consistently

Cargo.lock, flake.nix
Just backporting new substrate v0.9.26 deps to main from the release branch
=> Backport/release v0.10.21

.github/workflows/build-matrix.json, .github/workflows/build-nix.yml, .github/workflows/build.yml, .github/workflows/docker-nix.yml, .github/workflows/docker.yml, .github/workflows/docs.yml, .github/workflows/tests.yml, ci/script.sh
It is very useful for local & automated runtime upgrade wasm verification that some important events that happen on-chain are reduced in time, so they can verified quicker and potentially programatically.
This is a prerequisite to build an automated job that verifies runtime upgrades.
=> Test fast wasm build

libs/traits/src/lib.rs
This PR continues the work on https://github.com/centrifuge/centrifuge-chain/pull/1008, extending the ops with *assign* traits.
Before:
```rust
let mut my_long_variable_name: u32 = 0;
my_long_variable_name = my_long_variable_name.checked_sub(1).ok_or(ArithmeticError::Underflow)?;
```
After:
```rust
let mut my_long_variable_name: u32 = 0;
my_long_variable_name.ensure_sub_assign(1)?;
```
Addition of new ops traits into `libs/traits`:
- `EnsureAddAssign`
- `EnsureSubAssign`
- `EnsureMulAssign`
- `EnsureDivAssign`
- Correct multiplication underflow behavior
- Correct addition underflow behavior
- Correct subtraction overflow behavior
```sh
cargo test -p cfg-traits // Which will run the associated doc examples
```
=> Add EnsureOpsAssign traits

README.md, docs/DEVELOPING.md
=> Fix: typos

Cargo.lock, flake.nix, libs/traits/Cargo.toml, libs/traits/src/lib.rs, libs/traits/src/rewards.rs
Rewards trait used to interact with the pallet rewards.
Fixes https://github.com/centrifuge/centrifuge-chain/issues/1035
=> Rewards trait

pallets/liquidity-rewards/src/lib.rs, pallets/rewards/src/lib.rs, pallets/rewards/src/tests.rs
Some minor reward fixes/improvements
- Generalized error using `TokenError` from Substrate.
- Some code reorganizations to avoid a wrong state if the method fails.
```sh
```
=> Minor rewards fixes/improvements

Cargo.lock, Cargo.toml, flake.nix, libs/primitives/src/lib.rs, runtime/altair/Cargo.toml, runtime/altair/src/lib.rs, runtime/centrifuge/Cargo.toml, runtime/centrifuge/src/lib.rs, runtime/integration-tests/Cargo.toml, runtime/integration-tests/src/xcm/polkadot/tests/restricted_calls.rs
Release the #1067 and other minor adjustments
=> bump: Centrifuge 1015 + Altair 2023

pallets/rewards/src/lib.rs, pallets/rewards/src/mechanism.rs, pallets/rewards/src/mechanism/base.rs, pallets/rewards/src/mechanism/base_with_currency_movement.rs, pallets/rewards/src/mechanism/deferred.rs, pallets/rewards/src/mock.rs, pallets/rewards/src/tests.rs, pallets/rewards/src/tests/claiming.rs, pallets/rewards/src/tests/common.rs
Add the deferred mechanism for `pallet-rewards` based on [this proposal](https://docs.google.com/presentation/d/1EwEcsXVc5HLyULQehz1L-0XMOf7KGuvQWAYVgKcS2Qk/edit?pli=1#slide=id.g1613d09df7c_0_350)
Note: *The deferred mechanism encompasses deferred + reverted + reinjected phases of the proposal.*
Fixes #998
- Added a new mechanism
- Added test
- Add a generic & unique way to identify distributions (`DistributionId`).
```sh
```
=> Rewards: deferred mechanism implementation

pallets/rewards/README.md
This PR fix the undone comments of https://github.com/centrifuge/centrifuge-chain/pull/1094
=> Rewards: documentation fixes

pallets/pool-registry/src/lib.rs
=> Change pools storage hash

.github/workflows/benchmark.yml
Testing on comment gh action for benchmarks
=> test bench

.github/workflows/benchmark.yml
Testing pr comments for benchmarking
=> Attempt to fix pr comment for benchmarks

.github/workflows/benchmark.yml
Need to merge this to try it on PRs against main.
=> Hacky try to trigger action on comment

.github/workflows/benchmark.yml
Another attempt to make it work
=> N action on comment trial

.github/workflows/benchmark.yml
=> test n+2 benchmarks

.github/workflows/benchmark.yml
=> test n+4 benchmark

.github/workflows/benchmark.yml
=> Fix comment feedback step

.github/workflows/benchmark.yml
Removed artifact url retrieval, since `listWorkflowRunArtifacts` doesnt resolve while the job is running. 
Added a few visual icons.
=> Remove artifact code

.github/CODEOWNERS
This PR adds a CODEOWNER file to our repository. This alone does not enable anything but when the repository enforces code owners to do a review, only with a review of them PRs can be merged.
=> Adding Codeowners

Cargo.lock, Cargo.toml, flake.nix, runtime/altair/Cargo.toml, runtime/altair/src/lib.rs, runtime/centrifuge/Cargo.toml, runtime/centrifuge/src/lib.rs
Adapting Election Phragmen params
=> Adapt phragem params

runtime/development/src/lib.rs
Add a new proxy type that the onboarding API would use for adding new investors.
=> Add proxy type for permission management

ci/script.sh, libs/proofs/src/lib.rs, libs/test-utils/src/mocks/accountant.rs, libs/test-utils/src/mocks/nav.rs, libs/test-utils/src/mocks/order_manager.rs, libs/traits/src/rewards.rs, libs/types/src/fee_keys.rs, pallets/connectors/src/lib.rs, pallets/connectors/src/message.rs, pallets/connectors/src/routers.rs, pallets/interest-accrual/src/lib.rs, pallets/investments/src/lib.rs, pallets/liquidity-rewards/src/lib.rs, pallets/loans/src/functions.rs, pallets/loans/src/loan_type.rs, pallets/loans/src/types.rs, pallets/migration/src/lib.rs, pallets/nft-sales/src/lib.rs, pallets/pool-registry/src/lib.rs, pallets/pool-system/src/lib.rs, pallets/pool-system/src/pool_types.rs, pallets/pool-system/src/tranches.rs, pallets/rewards/src/lib.rs, pallets/rewards/src/mechanism.rs, pallets/rewards/src/mechanism/gap.rs, runtime/development/src/lib.rs, src/chain_spec.rs
* Set up a clippy command line that will actually fail the lint script
* Fix clippy errors that have appeared since our first time
All existing tests still build/run
=> Clippy take 2

pallets/interest-accrual/src/lib.rs
Add further documentation on the why and how of this pallet, especially focused on debt normalization and renormalization
Documentation-only change.
=> Add additional documentation to pallet-interest-accrual

.github/workflows/docker.yml
Clear up some unused packages so docker builds can complete
=> fix docker build - clean space

.github/workflows/tests.yml
_Originally posted by @mikiquantum in https://github.com/centrifuge/centrifuge-chain/issues/1238#issuecomment-1462182656_
Try fix over https://github.com/centrifuge/centrifuge-chain/pull/1238
=> Cleaning test CI job for debug cases

pallets/rewards/src/lib.rs
Storage names in pallets seem to be plural or singular based on the stored element instead of seeing it as a container (although I still don't know why 🤷🏻‍♂️). This PR standardizes the names of `pallet-rewards`, making them singular.
Storage names in singular
=> Standarize storage names in `pallet-rewards`

pallets/loans-ref/src/benchmarking.rs
Fixes https://github.com/centrifuge/centrifuge-chain-internal/issues/44
=> Pallet loans-ref: Fix policy benchmark

pallets/connectors/src/message.rs
NIT, just moving some tests around to follow the messages call index which is helpful when cross testing with the Solidity counter part.
=> connectors: Sort messages test by call index

Cargo.lock, libs/traits/src/lib.rs, pallets/investments/src/lib.rs, runtime/altair/src/lib.rs, runtime/centrifuge/src/lib.rs, runtime/common/Cargo.toml, runtime/common/src/apis/investments.rs, runtime/common/src/lib.rs, runtime/development/src/lib.rs
Please include a summary of the changes and the related issue. Please also include relevant motivation and context. List any dependencies that are required for this change.
Fixes # 941, partially -- adds runtime api for investments needed now, not all in issue at the moment.
Adds runtime api for investments to get currency and pool for an investment id.
=> Add initial runtime investments api call for pool/currency ids

pallets/liquidity-pools-gateway/routers/src/lib.rs, pallets/liquidity-pools-gateway/routers/src/tests.rs, runtime/integration-tests/src/liquidity_pools/gateway.rs, runtime/integration-tests/src/liquidity_pools/pallet/development/tests/liquidity_pools.rs, runtime/integration-tests/src/liquidity_pools/pallet/development/tests/routers/ethereum_xcm.rs
Allows to set the weights of the xcm router more granulary. This is especially importatnt to get a realistic max weight for the pov.
=> Feat: xcm router weights

.github/workflows/build.yml, Cargo.toml, ci/script.sh, runtime/altair/Cargo.toml, runtime/altair/src/lib.rs, runtime/altair/src/migrations.rs, src/chain_spec.rs, src/command.rs
Extends #1585 
* Adds Moonbase Alpha relay chain config
* Removes `Algol` remnants
* Removes `testnet-runtime` feature which was only used for Algol
=> refactor: add moonbeam alpha spec, remove algol

.github/workflows/deploy-docs.yml, .github/workflows/sanity-checks.yml, ci/run-check.sh
PR #1619 fixes publishing docs but now PRs cannot use the build-docs job. 
This PR fixes that and simplifies the PR checks code even more using matrixes.
=>  CI bug fixes - Part III

runtime/integration-tests/src/generic/cases/liquidity_pools.rs, runtime/integration-tests/src/generic/cases/proxy.rs, runtime/integration-tests/src/generic/config.rs, runtime/integration-tests/src/generic/envs/fudge_env/handle.rs, runtime/integration-tests/src/generic/mod.rs, runtime/integration-tests/src/generic/utils/currency.rs
From this [slack conversation](https://kflabs.slack.com/archives/C04GJQAM9P0/p1703688113169509)
=> Integration tests for proxies

Cargo.lock, runtime/development/Cargo.toml, runtime/development/src/lib.rs, runtime/development/src/migrations.rs
Just the version bumb. Should we bring this into main?
=> Development 1037

pallets/loans/src/benchmarking.rs, pallets/loans/src/lib.rs, pallets/loans/src/tests/borrow_loan.rs, pallets/loans/src/weights.rs, runtime/altair/src/weights/pallet_loans.rs, runtime/centrifuge/src/weights/pallet_loans.rs, runtime/development/src/weights/pallet_loans.rs
From this [slack conversation](https://kflabs.slack.com/archives/C04GJQAM9P0/p1704192846617889)
=> Loans: add `increase_debt()` action

.github/workflows/build-docker.yml, .github/workflows/build-wasm.yml, .github/workflows/deploy-docs.yml, .github/workflows/run-benchmarks.yml
Upgrade Github Actions dependencies
Closes #1709 #1710 #1711 #1712
=> Gha-upgrades

libs/types/src/domain_address.rs, pallets/liquidity-pools-gateway/axelar-gateway-precompile/src/lib.rs, runtime/integration-tests/src/generic/cases/lp/investments.rs, runtime/integration-tests/src/generic/cases/lp/mod.rs, runtime/integration-tests/src/generic/cases/lp/pool_management.rs, runtime/integration-tests/src/generic/config.rs, runtime/integration-tests/src/generic/env.rs, runtime/integration-tests/src/generic/envs/evm_env.rs, runtime/integration-tests/src/generic/envs/runtime_env.rs, runtime/integration-tests/src/generic/mod.rs, runtime/integration-tests/src/generic/utils/currency.rs, runtime/integration-tests/src/generic/utils/evm.rs
[description]
Fixes #(issue)
[List your changes here]
=> feat: new evm exposure

Cargo.lock, runtime/development/Cargo.toml, runtime/development/src/lib.rs, runtime/development/src/migrations.rs
Need to upgrade dev and demo environments as soon as possible. This preps it.
* bumbs versions
=> chore: bumb dev versions

Cargo.lock, runtime/integration-tests/Cargo.toml, runtime/integration-tests/src/generic/config.rs, runtime/integration-tests/src/generic/env.rs
Just a minor PR to fix IT in the base one
=> feat: CheckMetadataHash extension (IT fix)

codecov.yaml
Testing codecov fixes from lp-message-bincode
=> try to succeed job CI failures for codecov

codecov.yaml
https://kflabs.slack.com/archives/C04GJQAM9P0/p1718188938855999
=> Succeed when patch codecov fails

runtime/integration-tests/src/cases/lp/pool_management.rs, runtime/integration-tests/src/cases/lp/transfers.rs
Leave `feat/lp-v2` CI jobs in green without failures.
=> LPv2: ignore failing tests

pallets/liquidity-pools/src/tests.rs, runtime/integration-tests/src/cases/lp/setup_lp.rs
* Removes leftover from my previous PRs
=> refactor: cleanup my leftovers

.github/workflows/build-wasm.yml
[description]
Fixes #(issue)
[List your changes here]
=> Fix-wasm-upload

runtime/common/src/evm/mod.rs, runtime/integration-tests/src/cases/liquidity_pools.rs, runtime/integration-tests/src/cases/lp/investments.rs, runtime/integration-tests/src/cases/lp/pool_management.rs, runtime/integration-tests/src/cases/lp/setup_evm.rs, runtime/integration-tests/src/cases/lp/setup_lp.rs
* Updates Submodule to latest state
* Updates deploy setup
* Applied `UpdateTrancheHook` message requirement before investing for EVM
=> chore: update submodule
